import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';

const page=readFileSync('app/page.tsx','utf8'), header=readFileSync('components/editor/Header.tsx','utf8'), review=readFileSync('components/editor/CrewAIImportReview.tsx','utf8');

test('CrewAI import remains a separate picker from unchanged JSON import/drop',()=>{assert.match(header,/Import CrewAI|importCrewAI/);assert.match(header,/accept="\.py,text\/x-python"/);assert.match(header,/accept="\.json,application\/json"/);assert.match(page,/handleJsonDrop/);assert.doesNotMatch(page,/importGraphFile\(files\[0\].*CrewAI/);});
test('review provides dialog, focus, keyboard, live status and non-color labels',()=>{assert.match(review,/role="dialog"/);assert.match(review,/aria-modal="true"/);assert.match(review,/aria-labelledby/);assert.match(review,/aria-describedby/);assert.match(review,/e\.key\s*===\s*["']Escape["']/);assert.match(review,/e\.key\s*===\s*["']Tab["']/);assert.match(review,/aria-live="polite"/);assert.match(review,/aria-expanded=/);assert.match(review,/c\.status\[d\.status\]/);assert.match(review,/mapped:\s*["']Mapped["']/);assert.match(review,/lossy:\s*["']Lossy["']/);assert.match(review,/unknown:\s*["']Unknown["']/);assert.match(review,/unsupported:\s*["']Unsupported["']/);});
test('review is safe at 320px and actions meet touch target boundary',()=>{assert.match(review,/w-full/);assert.match(review,/h-\[100dvh\]/);assert.match(review,/overflow-x-hidden/);assert.match(review,/break-all|break-words/);assert.match(review,/min-h-11/);assert.match(page,/max-w-\[95vw\] overflow-x-auto/);});
test('atomic Apply uses current-state confirmation, Graph V1 persistence, history reset and bounded analytics',()=>{assert.match(page,/latestNodes\.current\.length/);assert.match(page,/window\.confirm/);assert.match(page,/historyRef\.current = \[\{ nodes: graph\.nodes, edges: graph\.edges \}\]/);assert.match(page,/serializeGraph\(graph\)/);assert.match(page,/trackEvent\('crewai_imported'/);assert.match(review,/disabled=\{result\.state\s*!==\s*["']READY["']\}/);});
test('EN remains intact and JA localizes all import-review labels and disclosures',()=>{assert.match(review,/Static analysis only/);assert.match(review,/静的解析のみ/);assert.match(review,/runtime version: Unknown/);assert.match(review,/ランタイムバージョン: 不明/);assert.match(review,/session-only/);assert.match(review,/セッション限定/);for(const label of ['ファイル','アダプター','マッピング済み','推定','欠損あり','不明','未対応','出典情報','準備完了','適用不可'])assert.match(review,new RegExp(label));});
