import { CustomNode, AgentNodeData, TaskNodeData, ToolNodeData, CrewConfig } from '@/types/editor';
import { Edge } from '@xyflow/react';

function toPythonIdentifier(str: string, fallback: string): string {
  const clean = str.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();
  const valid = clean.replace(/^[^a-zA-Z_]+/, '');
  return valid || fallback;
}

function escapePythonString(str: string): string {
  if (!str) return '""';
  if (str.includes('\n') || str.includes('"')) {
    const escaped = str.replace(/"""/g, '\\"\\"\\"');
    return `"""${escaped}"""`;
  }
  return `"${str}"`;
}

export function transpileToCrewAI(
  nodes: CustomNode[],
  edges: Edge[],
  crewConfig: CrewConfig = { name: 'My Crew', process: 'sequential', verbose: true, memory: false }
): string {
  const agentNodes = nodes.filter((n) => n.type === 'agent');
  const taskNodes = nodes.filter((n) => n.type === 'task');
  const toolNodes = nodes.filter((n) => n.type === 'tool');

  // Map tool imports needed
  const requiredTools = new Set<string>();
  toolNodes.forEach((tNode) => {
    const data = tNode.data as ToolNodeData;
    if (data.toolType && data.toolType !== 'CustomTool') {
      requiredTools.add(data.toolType);
    }
  });

  // Map tools to agents and tasks based on edges
  // Edges: source -> target
  const agentToolMap: Record<string, string[]> = {};
  const taskToolMap: Record<string, string[]> = {};
  const taskAgentMap: Record<string, string> = {};

  // Tool node variable names
  const toolVarNames: Record<string, string> = {};
  toolNodes.forEach((tNode, idx) => {
    const data = tNode.data as ToolNodeData;
    const baseName = data.label ? toPythonIdentifier(data.label, 'tool') : 'tool';
    const varName = `${baseName}_${idx + 1}`;
    toolVarNames[tNode.id] = varName;
  });

  // Agent node variable names
  const agentVarNames: Record<string, string> = {};
  agentNodes.forEach((aNode, idx) => {
    const data = aNode.data as AgentNodeData;
    const baseName = data.role ? toPythonIdentifier(data.role, 'agent') : 'agent';
    agentVarNames[aNode.id] = `${baseName}_agent`;
  });

  // Task node variable names
  const taskVarNames: Record<string, string> = {};
  // Sort tasks by Y coordinate to keep logical flow
  const sortedTaskNodes = [...taskNodes].sort((a, b) => a.position.y - b.position.y);
  sortedTaskNodes.forEach((tNode, idx) => {
    const data = tNode.data as TaskNodeData;
    const baseName = data.label ? toPythonIdentifier(data.label, 'task') : `task_${idx + 1}`;
    taskVarNames[tNode.id] = `${baseName}_task`;
  });

  // Process connections
  edges.forEach((edge) => {
    const sourceNode = nodes.find((n) => n.id === edge.source);
    const targetNode = nodes.find((n) => n.id === edge.target);

    if (!sourceNode || !targetNode) return;

    // Tool -> Agent
    if (sourceNode.type === 'tool' && targetNode.type === 'agent') {
      if (!agentToolMap[targetNode.id]) agentToolMap[targetNode.id] = [];
      agentToolMap[targetNode.id].push(toolVarNames[sourceNode.id]);
    }
    // Tool -> Task
    else if (sourceNode.type === 'tool' && targetNode.type === 'task') {
      if (!taskToolMap[targetNode.id]) taskToolMap[targetNode.id] = [];
      taskToolMap[targetNode.id].push(toolVarNames[sourceNode.id]);
    }
    // Agent -> Task
    else if (sourceNode.type === 'agent' && targetNode.type === 'task') {
      taskAgentMap[targetNode.id] = agentVarNames[sourceNode.id];
    }
    // Task -> Agent
    else if (sourceNode.type === 'task' && targetNode.type === 'agent') {
      taskAgentMap[sourceNode.id] = agentVarNames[targetNode.id];
    }
  });

  // Also check assignedAgentId inside task data if edge was not drawn
  taskNodes.forEach((tNode) => {
    const data = tNode.data as TaskNodeData;
    if (!taskAgentMap[tNode.id] && data.assignedAgentId && agentVarNames[data.assignedAgentId]) {
      taskAgentMap[tNode.id] = agentVarNames[data.assignedAgentId];
    }
  });

  // Code sections build up
  let code = `# ==============================================================================
# Code generated by AgentGraph Studio
# CrewAI Autonomous Agent Flow: ${crewConfig.name}
# ==============================================================================

import os
from crewai import Agent, Task, Crew, Process
`;

  // Tools import
  if (requiredTools.size > 0) {
    code += `from crewai_tools import (\n  ${Array.from(requiredTools).join(',\n  ')}\n)\n`;
  }

  code += `\n# ------------------------------------------------------------------------------
# 1. API Keys & Environment Configuration
# Make sure to set your LLM and tool API keys before execution.
# ------------------------------------------------------------------------------
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY", "YOUR_OPENAI_API_KEY")
`;

  if (requiredTools.has('SerperDevTool')) {
    code += `os.environ["SERPER_API_KEY"] = os.getenv("SERPER_API_KEY", "YOUR_SERPER_API_KEY")\n`;
  }

  // Instantiating Tools
  code += `\n# ------------------------------------------------------------------------------
# 2. Tools Instantiation
# ------------------------------------------------------------------------------
`;

  if (toolNodes.length === 0) {
    code += `# No tools connected in current graph\n`;
  } else {
    toolNodes.forEach((tNode) => {
      const data = tNode.data as ToolNodeData;
      const varName = toolVarNames[tNode.id];
      if (data.toolType === 'CustomTool') {
        code += `# Custom Tool: ${data.label}\n${varName} = None  # Replace with custom tool instance\n`;
      } else {
        code += `${varName} = ${data.toolType}()\n`;
      }
    });
  }

  // Instantiating Agents
  code += `\n# ------------------------------------------------------------------------------
# 3. Agents Definition
# ------------------------------------------------------------------------------
`;

  if (agentNodes.length === 0) {
    code += `# Warning: No Agent nodes defined in graph\n`;
  } else {
    agentNodes.forEach((aNode) => {
      const data = aNode.data as AgentNodeData;
      const varName = agentVarNames[aNode.id];
      const toolsList = agentToolMap[aNode.id] ? `[${agentToolMap[aNode.id].join(', ')}]` : '[]';

      code += `${varName} = Agent(
    role=${escapePythonString(data.role || 'AI Agent')},
    goal=${escapePythonString(data.goal || 'Achieve objective')},
    backstory=${escapePythonString(data.backstory || 'An intelligent assistant.')},
    verbose=${data.verbose ? 'True' : 'False'},
    allow_delegation=${data.allowDelegation ? 'True' : 'False'},
    tools=${toolsList},
    llm=${escapePythonString(data.model || 'gpt-4o')}
)

`;
    });
  }

  // Instantiating Tasks
  code += `# ------------------------------------------------------------------------------
# 4. Tasks Definition
# ------------------------------------------------------------------------------
`;

  if (sortedTaskNodes.length === 0) {
    code += `# Warning: No Task nodes defined in graph\n`;
  } else {
    sortedTaskNodes.forEach((tNode) => {
      const data = tNode.data as TaskNodeData;
      const varName = taskVarNames[tNode.id];
      const assignedAgent = taskAgentMap[tNode.id] || (agentNodes.length > 0 ? agentVarNames[agentNodes[0].id] : 'None');
      const toolsList = taskToolMap[tNode.id] ? `, tools=[${taskToolMap[tNode.id].join(', ')}]` : '';

      code += `${varName} = Task(
    description=${escapePythonString(data.description || 'Perform task')},
    expected_output=${escapePythonString(data.expectedOutput || 'Task result summary')},
    agent=${assignedAgent}${toolsList},
    async_execution=${data.asyncExecution ? 'True' : 'False'}
)

`;
    });
  }

  // Crew & Process Assembly
  const allAgentsList = agentNodes.map((a) => agentVarNames[a.id]).join(', ');
  const allTasksList = sortedTaskNodes.map((t) => taskVarNames[t.id]).join(', ');
  const processType = crewConfig.process === 'hierarchical' ? 'Process.hierarchical' : 'Process.sequential';

  code += `# ------------------------------------------------------------------------------
# 5. Crew Assembly & Execution
# ------------------------------------------------------------------------------
crew = Crew(
    agents=[${allAgentsList}],
    tasks=[${allTasksList}],
    process=${processType},
    verbose=${crewConfig.verbose ? 'True' : 'False'},
    memory=${crewConfig.memory ? 'True' : 'False'}
)

if __name__ == "__main__":
    print("🚀 Starting AgentGraph Studio Crew execution...")
    result = crew.kickoff()
    print("\\n" + "=" * 60)
    print("🎯 FINAL CREW EXECUTION OUTPUT:")
    print("=" * 60)
    print(result)
`;

  return code;
}
