import {
  CustomNode,
  AgentNodeData,
  TaskNodeData,
  ToolNodeData,
  CrewConfig,
  ExportMode,
  ProjectFile,
  ProjectExportResult,
} from '@/types/editor';
import { Edge } from '@xyflow/react';
import {
  validateGraph,
  toPythonIdentifier,
} from './validation';
import { parseOutputSchema } from './output-schema';
import { createCodegenPlan, normalizeModel } from './codegen-plan';
import { getToolParameterDefinitions } from '@/lib/tool-config';

export { normalizeModel } from './codegen-plan';

export function escapePythonString(str?: string): string {
  return JSON.stringify(str || '')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function escapeCrewAIInterpolation(str: string | undefined, inputVariables: string[]): string {
  let escaped = String(str || '').replace(/\{/g, '{{').replace(/\}/g, '}}');
  inputVariables.forEach((variable) => {
    escaped = escaped.replaceAll(`{{${variable}}}`, `{${variable}}`);
  });
  return escaped;
}

function renderSchemaFields(data?: TaskNodeData): string {
  const fields = parseOutputSchema(data?.outputSchema);
  if (!fields) return '    result: dict[str, Any] = Field(description="Structured task result matching the requested output")';
  return Object.entries(fields)
    .map(([name, type]) => `    ${name}: ${type}`)
    .join('\n');
}

function suggestedInputValue(variable: string): string {
  const lower = variable.toLowerCase();
  if (lower.endsWith('_path') || lower.endsWith('_directory') || lower.endsWith('_file')) return './';
  if (lower.endsWith('_url') || lower.endsWith('_urls')) return 'https://example.com';
  if (lower.includes('language')) return 'Japanese';
  if (lower.includes('length')) return '1200';
  return `Replace with ${variable.replace(/_/g, ' ')}`;
}

export function getRequiredEnvVars(nodes: CustomNode[], crewConfig?: CrewConfig): string[] {
  const keys = new Set<string>();
  let sawModel = false;

  const checkModel = (modelStr?: string) => {
    sawModel = true;
    const m = normalizeModel(modelStr).toLowerCase();
    if (m.startsWith('openai/')) keys.add('OPENAI_API_KEY');
    else if (m.startsWith('anthropic/')) keys.add('ANTHROPIC_API_KEY');
    else if (m.startsWith('gemini/')) keys.add('GEMINI_API_KEY');
    else if (m.startsWith('groq/')) keys.add('GROQ_API_KEY');
    else if (m.startsWith('deepseek/')) keys.add('DEEPSEEK_API_KEY');
  };

  if (crewConfig?.process === 'hierarchical') {
    checkModel(crewConfig.managerLlm);
  }

  (nodes || []).forEach((node) => {
    if (node?.type === 'agent') {
      const data = node.data as AgentNodeData;
      checkModel(data?.model);
    } else if (node?.type === 'tool') {
      const data = node.data as ToolNodeData;
      if (data?.toolType === 'SerperDevTool') keys.add('SERPER_API_KEY');
      if (data?.toolType === 'GithubSearchTool') keys.add('GITHUB_TOKEN');
    }
  });

  if (crewConfig?.memory) keys.add('OPENAI_API_KEY');
  const ragToolTypes = new Set(['CSVSearchTool', 'TXTSearchTool', 'PDFSearchTool', 'MDXSearchTool']);
  if ((nodes || []).some((node) => node.type === 'tool' && ragToolTypes.has(String((node.data as ToolNodeData)?.toolType)))) {
    keys.add('OPENAI_API_KEY');
  }

  if (keys.size === 0 && !sawModel) {
    keys.add('OPENAI_API_KEY');
  }

  return Array.from(keys).sort();
}

export function transpileToCrewAI(
  nodes: CustomNode[] = [],
  edges: Edge[] = [],
  crewConfig: CrewConfig = { name: 'My Crew', process: 'sequential', verbose: true, memory: false },
  mode: ExportMode = 'scaffold',
  projectLayout = false
): string {
  const validation = validateGraph(nodes, edges, crewConfig, mode);
  if (!validation.isValid) {
    const errorDetails = validation.errors.map((e) => `- [${e.code}] ${e.message}`).join('\n');
    throw new Error(`Graph validation failed:\n${errorDetails}`);
  }

  const plan = createCodegenPlan(nodes, edges, crewConfig, validation);
  const agentNodes = plan.agents;
  const taskNodes = plan.tasksById;
  const toolNodes = plan.tools;
  const requiredPrebuiltTools = plan.prebuiltToolTypes;
  const customToolList = plan.customTools;
  const { toolVarNames, agentVarNames, taskVarNames, structuredTaskSchemas, agentToolMap, taskToolMap } = plan;
  const usedModelsMap = new Map(plan.models.map(({ model, varName }) => [model, varName]));
  const agentModelNormalized = plan.agentModels;
  const managerModelNormalized = plan.managerModel;

  // Environment checks
  const requiredEnvVars = getRequiredEnvVars(nodes, crewConfig);

  // Build Code Header
  let code = `# ==============================================================================
# Code generated by AgentGraph Studio
# CrewAI Autonomous Agent Flow: ${crewConfig?.name || 'My Crew'}
# Mode: ${mode === 'production' ? 'Production' : 'Scaffold (Stubs included)'}
# ==============================================================================

import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
`;

  if (customToolList.length > 0) {
    code += projectLayout
      ? `from tools.custom_tools import ${customToolList.map((tool) => tool.className).join(', ')}\n`
      : `from crewai.tools import BaseTool\n`;
  }

  const schemaNames = Object.values(structuredTaskSchemas);
  if (schemaNames.length > 0) {
    code += projectLayout
      ? `from schemas import ${schemaNames.join(', ')}\n`
      : `from pydantic import BaseModel, Field\nfrom typing import Any\n`;
  }

  if (requiredPrebuiltTools.length > 0) {
    code += `from crewai_tools import (\n    ${requiredPrebuiltTools.join(',\n    ')}\n)\n`;
  }

  // 1. Environment & API Keys
  code += `\n# ------------------------------------------------------------------------------
# 1. API Keys & Environment Configuration
# ------------------------------------------------------------------------------
# Load environment variables securely from .env file
load_dotenv()

REQUIRED_ENV_VARS = [
${requiredEnvVars.map((k) => `    "${k}",`).join('\n')}
]

missing_vars = [var for var in REQUIRED_ENV_VARS if not os.getenv(var)]
if missing_vars:
    raise RuntimeError(
        f"Missing required environment variable(s): {', '.join(missing_vars)}. "
        "Please create a .env file based on .env.example."
    )
`;

  // 2. Custom Tools (BaseTool Stubs) & Prebuilt Tool Instantiation
  code += `\n# ------------------------------------------------------------------------------
# 2. Tools Instantiation
# ------------------------------------------------------------------------------
`;

  if (customToolList.length > 0 && !projectLayout) {
    code += `# --- Custom Tool Stubs (Inherits from BaseTool) ---\n`;
    customToolList.forEach((ct) => {
      code += `class ${ct.className}(BaseTool):
    name: str = "${ct.varName}"
    description: str = ${escapePythonString(ct.description)}

    def _run(self, *args, **kwargs) -> str:
        """Execute custom tool logic for ${ct.label}."""
        # TODO: Implement production execution logic here
        raise NotImplementedError(
            "${ct.className} is a scaffold tool. Implement execution logic before production execution."
        )


`;
    });
  }

  if (schemaNames.length > 0 && !projectLayout) {
    code += `# --- Structured output schemas ---\n`;
    Object.entries(structuredTaskSchemas).forEach(([taskId, className]) => {
      const task = taskNodes.find((node) => node.id === taskId);
      const taskData = task?.data as TaskNodeData;
      const taskLabel = String(taskData?.label || taskId).replace(/"""/g, '');
      code += `class ${className}(BaseModel):
    """Validated output for ${taskLabel}."""
${renderSchemaFields(taskData)}


`;
    });
  }

  if (toolNodes.length === 0) {
    code += `# No tools connected in current graph\n`;
  } else {
    toolNodes.forEach((tNode) => {
      const data = (tNode?.data || {}) as ToolNodeData;
      const varName = toolVarNames[tNode.id];
      if (data?.toolType === 'CustomTool') {
        const ct = customToolList.find((c) => c.id === tNode.id);
        const className = ct?.className || 'CustomTool';
        code += `${varName} = ${className}()\n`;
      } else {
        const toolType = data?.toolType || 'SerperDevTool';
        const parameters = getToolParameterDefinitions(data.toolType)
          .map(({ key }) => [key, data.parameters?.[key]] as const)
          .filter(([, value]) => String(value || '').trim())
          .map(([key, value]) => `${key}=${escapePythonString(escapeCrewAIInterpolation(String(value), validation.inputVariables))}`)
          .join(', ');
        code += `${varName} = ${toolType}(${parameters})\n`;
      }
    });
  }

  // 3. LLM Configurations
  code += `\n# ------------------------------------------------------------------------------
# 3. LLM Configurations
# ------------------------------------------------------------------------------
`;

  usedModelsMap.forEach((varName, modelStr) => {
    const ollamaBaseUrl = modelStr.startsWith('ollama/') ? '\n    base_url="http://localhost:11434",' : '';
    code += `${varName} = LLM(
    model="${modelStr}",${ollamaBaseUrl}
    temperature=0.1
)

`;
  });

  // 4. Agents Definition
  code += `# ------------------------------------------------------------------------------
# 4. Agents Definition
# ------------------------------------------------------------------------------
`;

  if (agentNodes.length === 0) {
    code += `# Warning: No Agent nodes defined in graph\n`;
  } else {
    agentNodes.forEach((aNode) => {
      const data = (aNode?.data || {}) as AgentNodeData;
      const varName = agentVarNames[aNode.id];
      const toolsList = agentToolMap[aNode.id] && agentToolMap[aNode.id].length > 0
        ? `[${agentToolMap[aNode.id].join(', ')}]`
        : '[]';

      const normModel = agentModelNormalized[aNode.id];
      const llmVarName = usedModelsMap.get(normModel) || 'llm';
      const executionGuards = plan.agentExecutionGuards[aNode.id];

      code += `${varName} = Agent(
    role=${escapePythonString(escapeCrewAIInterpolation(data?.role || 'AI Agent', validation.inputVariables))},
    goal=${escapePythonString(escapeCrewAIInterpolation(data?.goal || 'Achieve objective', validation.inputVariables))},
    backstory=${escapePythonString(escapeCrewAIInterpolation(data?.backstory || 'An intelligent assistant.', validation.inputVariables))},
    verbose=${data?.verbose !== false ? 'True' : 'False'},
    allow_delegation=${data?.allowDelegation ? 'True' : 'False'},
    tools=${toolsList},
    llm=${llmVarName},
    max_iter=${executionGuards.maxIter.value},
    max_rpm=${executionGuards.maxRpm.value ?? 'None'},
    max_execution_time=${executionGuards.maxExecutionTime.value ?? 'None'},
    respect_context_window=${data?.respectContextWindow !== false ? 'True' : 'False'},
    cache=${data?.cache !== false ? 'True' : 'False'}
)

`;
    });
  }

  // 5. Tasks Definition (with context and ordered by topological sort)
  code += `# ------------------------------------------------------------------------------
# 5. Tasks Definition
# ------------------------------------------------------------------------------
`;

  const sortedTaskNodes = plan.executionTasks;

  if (sortedTaskNodes.length === 0) {
    code += `# Warning: No Task nodes defined in graph\n`;
  } else {
    sortedTaskNodes.forEach((tNode) => {
      const data = (tNode?.data || {}) as TaskNodeData;
      const varName = taskVarNames[tNode.id];
      const assignment = plan.taskAssignments[tNode.id];
      const assignedAgentVar = assignment?.kind === 'fixed' ? agentVarNames[assignment.agentId] : undefined;

      const toolsList = taskToolMap[tNode.id] && taskToolMap[tNode.id].length > 0
        ? `tools=[${taskToolMap[tNode.id].join(', ')}],\n    `
        : '';

      const predecessorIds = plan.taskContextMap[tNode.id] || [];
      const contextList = predecessorIds.length > 0
        ? `context=[${predecessorIds.map((pId) => taskVarNames[pId]).filter(Boolean).join(', ')}],\n    `
        : '';
      const outputSchema = structuredTaskSchemas[tNode.id]
        ? `output_pydantic=${structuredTaskSchemas[tNode.id]},\n    `
        : '';
      const outputOptions = [
        data?.markdown ? 'markdown=True' : '',
        data?.outputFile?.trim() ? `output_file=${escapePythonString(data.outputFile.trim())}` : '',
        data?.humanInput ? 'human_input=True' : '',
      ].filter(Boolean).map((option) => `${option},\n    `).join('');

      let agentAssignment = '';
      if (assignment?.kind === 'fixed' && assignedAgentVar) {
        agentAssignment = `agent=${assignedAgentVar},\n    `;
      }

      code += `${varName} = Task(
    description=${escapePythonString(escapeCrewAIInterpolation(data?.description || 'Perform task', validation.inputVariables))},
    expected_output=${escapePythonString(escapeCrewAIInterpolation(data?.expectedOutput || 'Task result summary', validation.inputVariables))},
    ${agentAssignment}${toolsList}${contextList}${outputSchema}${outputOptions}async_execution=${data?.asyncExecution ? 'True' : 'False'}
)

`;
    });
  }

  // 6. Crew Assembly & Execution
  const allAgentsList = agentNodes.map((a) => agentVarNames[a.id]).join(', ');
  const allTasksList = sortedTaskNodes.map((t) => taskVarNames[t.id]).join(', ');
  const processType = crewConfig?.process === 'hierarchical' ? 'Process.hierarchical' : 'Process.sequential';

  let managerLlmStr = '';
  if (crewConfig?.process === 'hierarchical' && managerModelNormalized) {
    const managerVar = plan.managerLlmVar;
    managerLlmStr = `\n    manager_llm=${managerVar},`;
  }

  const inputVars = validation.inputVariables;
  let executionBlock = '';
  if (inputVars.length > 0) {
    const inputsFormatted = inputVars.map((v) => `        "${v}": ${escapePythonString(suggestedInputValue(v))},`).join('\n');
    executionBlock = `    inputs = {\n${inputsFormatted}\n    }\n    result = crew.kickoff(inputs=inputs)\n`;
  } else {
    executionBlock = `    result = crew.kickoff()\n`;
  }

  code += `# ------------------------------------------------------------------------------
# 6. Crew Assembly & Execution
# ------------------------------------------------------------------------------
crew = Crew(
    agents=[${allAgentsList}],
    tasks=[${allTasksList}],
    process=${processType},${managerLlmStr}
    verbose=${crewConfig?.verbose !== false ? 'True' : 'False'},
    memory=${crewConfig?.memory ? 'True' : 'False'}
)

if __name__ == "__main__":
    print("🚀 Starting AgentGraph Studio Crew execution...")
${executionBlock}    print("\\n" + "=" * 60)
    print("🎯 FINAL CREW EXECUTION OUTPUT:")
    print("=" * 60)
    print(result)
`;

  return code;
}

export function generateProjectFiles(
  nodes: CustomNode[] = [],
  edges: Edge[] = [],
  crewConfig: CrewConfig = { name: 'My Crew', process: 'sequential', verbose: true, memory: false },
  mode: ExportMode = 'scaffold'
): ProjectExportResult {
  const validation = validateGraph(nodes, edges, crewConfig, mode);
  if (!validation.isValid) {
    return {
      mode,
      validation,
      files: [],
      mainCode: '',
    };
  }

  const mainCode = transpileToCrewAI(nodes, edges, crewConfig, mode, true);
  const plan = createCodegenPlan(nodes, edges, crewConfig, validation);

  const files: ProjectFile[] = [];

  // 1. main.py
  files.push({
    path: 'main.py',
    filename: 'main.py',
    content: mainCode,
    language: 'python',
    description: 'Main CrewAI execution entrypoint',
  });

  // 2. tools/custom_tools.py
  if (validation.customTools.length > 0) {
    let customToolsContent = `# Custom Tool Implementations for ${crewConfig.name}
from crewai.tools import BaseTool
from pydantic import Field

`;
    validation.customTools.forEach((ct) => {
      customToolsContent += `class ${ct.className}(BaseTool):
    name: str = "${ct.varName}"
    description: str = ${escapePythonString(ct.description)}

    def _run(self, *args, **kwargs) -> str:
        """Domain execution logic for ${ct.label}."""
        # TODO: Implement your custom tool execution here
        raise NotImplementedError(
            "${ct.className} is not implemented. Please provide custom tool logic."
        )


`;
    });

    files.push({
      path: 'tools/custom_tools.py',
      filename: 'custom_tools.py',
      content: customToolsContent,
      language: 'python',
      description: 'Custom BaseTool stub implementations',
    });
    files.push({
      path: 'tools/__init__.py',
      filename: '__init__.py',
      content: '# AgentGraph Studio custom tools package\n',
      language: 'python',
      description: 'Marks the custom tools directory as a Python package',
    });
  }

  // 3. schemas.py
  let schemasContent = `# Pydantic Output Schemas for ${crewConfig.name}
from pydantic import BaseModel, Field
from typing import Any

`;

  plan.tasksById.forEach((t) => {
      const data = t.data as TaskNodeData;
    if (data.outputFormat === 'json') {
      const className = plan.structuredTaskSchemas[t.id];
      schemasContent += `class ${className}(BaseModel):
    """Structured output schema for task: ${data.label || t.id}."""
${renderSchemaFields(data)}


`;
    }
  });

  files.push({
    path: 'schemas.py',
    filename: 'schemas.py',
    content: schemasContent,
    language: 'python',
    description: 'Pydantic data models for structured task outputs',
  });

  // 4. .env.example
  const requiredEnvVars = getRequiredEnvVars(nodes, crewConfig);
  const envExampleContent = `# Environment Configuration for ${crewConfig.name}
# Copy this file to .env and fill in your actual API keys.
${requiredEnvVars.map((k) => `${k}=your_${k.toLowerCase()}_here`).join('\n')}
`;

  files.push({
    path: '.env.example',
    filename: '.env.example',
    content: envExampleContent,
    language: 'bash',
    description: 'Template for required environment variables',
  });

  // 5. requirements.txt
  const requirementsContent = `# Python Dependencies for CrewAI Workflow: ${crewConfig.name}
crewai>=1.15,<2
crewai-tools>=1.15,<2
pydantic>=2.7.0
python-dotenv>=1.0.1
`;

  files.push({
    path: 'requirements.txt',
    filename: 'requirements.txt',
    content: requirementsContent,
    language: 'text',
    description: 'Python package dependencies',
  });

  // 6. pyproject.toml
  const pyprojectContent = `[project]
name = "${toPythonIdentifier(crewConfig.name, 'crewai_flow')}"
version = "0.1.0"
description = "Autonomous Agent Workflow generated by AgentGraph Studio"
authors = [{ name = "AgentGraph Studio User" }]
dependencies = [
    "crewai>=1.15,<2",
    "crewai-tools>=1.15,<2",
    "pydantic>=2.7.0",
    "python-dotenv>=1.0.1",
]
requires-python = ">=3.10,<3.14"

[tool.crewai]
type = "crew"

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
`;

  files.push({
    path: 'pyproject.toml',
    filename: 'pyproject.toml',
    content: pyprojectContent,
    language: 'toml',
    description: 'Modern Python project definition',
  });

  // 7. README.md
  const readmeContent = `# 🚀 ${crewConfig.name} (CrewAI Workflow)

Generated by **AgentGraph Studio**.

## Quick Start

### 1. Setup Virtual Environment
\`\`\`bash
python3 -m venv venv
source venv/bin/activate  # On Windows: .\\venv\\Scripts\\activate
pip install -r requirements.txt
\`\`\`

### 2. Configure Environment Variables
\`\`\`bash
cp .env.example .env
# Open .env and add your valid API keys:
# ${requiredEnvVars.join(', ')}
\`\`\`

### 3. Run Workflow
\`\`\`bash
python main.py
\`\`\`

## Graph Summary
- **Process**: \`${crewConfig.process}\`
- **Agents**: ${nodes.filter((n) => n.type === 'agent').length}
- **Tasks**: ${nodes.filter((n) => n.type === 'task').length}
- **Tools**: ${nodes.filter((n) => n.type === 'tool').length}
- **Export Mode**: \`${mode.toUpperCase()}\`
${validation.inputVariables.length > 0 ? `
## Required Workflow Inputs
Edit the \`inputs\` dictionary in \`main.py\` before running:
${validation.inputVariables.map((variable) => `- \`${variable}\`: ${suggestedInputValue(variable)}`).join('\n')}
` : ''}
`;

  files.push({
    path: 'README.md',
    filename: 'README.md',
    content: readmeContent,
    language: 'markdown',
    description: 'Setup and execution guide',
  });

  // 8. tests/test_crew.py
  const testCrewContent = `import unittest
from main import crew

class TestCrewWorkflow(unittest.TestCase):
    def test_crew_initialization(self):
        """Verify that the Crew and agents/tasks initialize properly."""
        self.assertIsNotNone(crew)
        self.assertGreater(len(crew.agents), 0)
        self.assertGreater(len(crew.tasks), 0)

if __name__ == "__main__":
    unittest.main()
`;

  files.push({
    path: 'tests/test_crew.py',
    filename: 'test_crew.py',
    content: testCrewContent,
    language: 'python',
    description: 'Basic integration test scaffold',
  });

  return {
    mode,
    validation,
    files,
    mainCode,
  };
}
