import { WorkflowTemplate, GraphData } from '@/types/editor';

export const PRESET_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'tech-research-writer',
    title: '🚀 Tech Research & Content Writer Crew',
    description: 'Automated 2-agent pipeline that conducts web research using Serper/Scraper tools and drafts published tech articles.',
    price: 0,
    category: 'Content Creation',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'Tech Research & Writer Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-1',
          type: 'tool',
          position: { x: 50, y: 80 },
          data: {
            label: 'Google Search API',
            toolType: 'SerperDevTool',
            description: 'Search live Google results for latest news & articles.',
          },
        },
        {
          id: 'tool-2',
          type: 'tool',
          position: { x: 50, y: 220 },
          data: {
            label: 'Web Scraper Tool',
            toolType: 'ScrapeWebsiteTool',
            description: 'Scrape full page contents from targeted web URLs.',
          },
        },
        {
          id: 'agent-1',
          type: 'agent',
          position: { x: 340, y: 120 },
          data: {
            label: 'Research Specialist',
            role: 'Senior Tech Researcher',
            goal: 'Uncover cutting-edge developments in AI technology and synthesize key technical trends.',
            backstory: 'A veteran technologist with a keen eye for groundbreaking innovation and technical accuracy.',
            model: 'gpt-4o',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-2',
          type: 'agent',
          position: { x: 340, y: 380 },
          data: {
            label: 'Content Strategist',
            role: 'Lead Tech Copywriter',
            goal: 'Transform dense research reports into engaging, publication-ready Markdown blog articles.',
            backstory: 'An expert tech journalist proficient in storytelling, SEO optimization, and audience retention.',
            model: 'gpt-4o',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-1',
          type: 'task',
          position: { x: 680, y: 120 },
          data: {
            label: 'Perform Web Research',
            description: 'Search for recent breakthroughs in autonomous multi-agent AI frameworks (CrewAI, AutoGen, LangGraph). Summarize 5 major architectural patterns.',
            expectedOutput: 'A structured bullet-point report containing 5 key breakthroughs, technical pros/cons, and reference links.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-2',
          type: 'task',
          position: { x: 680, y: 380 },
          data: {
            label: 'Draft Markdown Article',
            description: 'Based on the research findings, write a 600-word comprehensive technical blog post with subheadings and key takeaways.',
            expectedOutput: 'A complete, clean Markdown document with an engaging title, table of contents, and conclusion.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'tool-1', target: 'agent-1' },
        { id: 'e2', source: 'tool-2', target: 'agent-1' },
        { id: 'e3', source: 'agent-1', target: 'task-1' },
        { id: 'e4', source: 'agent-2', target: 'task-2' },
        { id: 'e5', source: 'task-1', target: 'task-2' },
      ],
    },
  },
  {
    id: 'code-audit-refactor',
    title: '🛡️ Automated Code Auditor & Security Refactor',
    description: '3-node workflow that inspects local directories, identifies security flaws, and outputs refactored code with unit tests.',
    price: 0,
    category: 'Engineering',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'Code Security & Refactor Crew',
        process: 'sequential',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-3',
          type: 'tool',
          position: { x: 50, y: 100 },
          data: {
            label: 'Directory Inspector',
            toolType: 'DirectoryReadTool',
            description: 'Scans files and subdirectories in target project folder.',
          },
        },
        {
          id: 'tool-4',
          type: 'tool',
          position: { x: 50, y: 240 },
          data: {
            label: 'File Reader',
            toolType: 'FileReadTool',
            description: 'Reads contents of target source code files.',
          },
        },
        {
          id: 'agent-3',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Security Auditor',
            role: 'Principal Application Security Engineer',
            goal: 'Identify vulnerabilities, race conditions, OWASP Top 10 risks, and anti-patterns in the codebase.',
            backstory: 'A seasoned hacker turned defender who specializes in static code analysis and exploit mitigation.',
            model: 'claude-3-5-sonnet-20240620',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-4',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Refactoring Engineer',
            role: 'Senior Software Architect',
            goal: 'Refactor problematic code into modular, type-safe, performant Python modules with pytest coverage.',
            backstory: 'Clean code zealot passionate about design patterns, solid architecture, and unit testing.',
            model: 'gpt-4o',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-3',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Audit Codebase',
            description: 'Scan source files in the project folder and log all security concerns, severity ratings, and line references.',
            expectedOutput: 'Security Audit Report with Severity (High/Med/Low), Vulnerability Description, and Recommended Fixes.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-4',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Generate Refactored Modules & Tests',
            description: 'Rewrite identified vulnerable snippets into safe code. Provide complete Python files and corresponding test suite.',
            expectedOutput: 'Refactored code snippets and pytest unit test blocks.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e6', source: 'tool-3', target: 'agent-3' },
        { id: 'e7', source: 'tool-4', target: 'agent-3' },
        { id: 'e8', source: 'agent-3', target: 'task-3' },
        { id: 'e9', source: 'agent-4', target: 'task-4' },
        { id: 'e10', source: 'task-3', target: 'task-4' },
      ],
    },
  },
  {
    id: 'market-financial-analyst',
    title: '📊 Financial Market Intelligence & Stock Analyst',
    description: 'Gather stock metrics, market sentiments, and competitor data to synthesize Wall St. style investment memos.',
    price: 0,
    category: 'Finance',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Financial Intelligence Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-5',
          type: 'tool',
          position: { x: 50, y: 150 },
          data: {
            label: 'Market Search Tool',
            toolType: 'SerperDevTool',
            description: 'Fetch financial news, quarterly earnings summaries, and stock press releases.',
          },
        },
        {
          id: 'agent-5',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Financial Analyst',
            role: 'Wall Street Research Analyst',
            goal: 'Analyze financial ratios, quarterly earnings reports, and macro tailwinds for target tech stocks.',
            backstory: 'Former equity research associate at a top investment bank known for quantitative accuracy.',
            model: 'gpt-4o',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-6',
          type: 'agent',
          position: { x: 340, y: 380 },
          data: {
            label: 'Portfolio Manager',
            role: 'Chief Investment Officer',
            goal: 'Synthesize raw financial metrics into a clear Investment Recommendation Memo (Buy/Hold/Sell) with risk disclosures.',
            backstory: 'Hedge fund manager with 15 years experience balancing growth opportunities against macroeconomic risks.',
            model: 'gpt-4o',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-5',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Gather Financial Metrics & News',
            description: 'Search recent earnings calls, P/E ratios, revenue growth metrics, and market sentiment for NVDA and MSFT.',
            expectedOutput: 'Financial summary matrix including revenue growth, margins, P/E ratio, and main catalysts.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-6',
          type: 'task',
          position: { x: 680, y: 380 },
          data: {
            label: 'Draft Executive Investment Memo',
            description: 'Synthesize the metrics into an executive memo featuring Rating, Price Target rationale, Bull/Bear thesis, and Key Risks.',
            expectedOutput: 'A 2-page formal Investment Memo suitable for board members or fund investors.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e11', source: 'tool-5', target: 'agent-5' },
        { id: 'e12', source: 'agent-5', target: 'task-5' },
        { id: 'e13', source: 'agent-6', target: 'task-6' },
        { id: 'e14', source: 'task-5', target: 'task-6' },
      ],
    },
  },
];
