import { CustomNode, WorkflowTemplate } from '@/types/editor';
import { Edge } from '@xyflow/react';

const BASE_PRESET_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'x-trend-auto-poster',
    title: '📱 X (Twitter) Trend Analyst & Auto-Poster',
    titleEn: '📱 X (Twitter) Trend Analyst & Auto-Poster',
    titleJa: '📱 X (Twitter) トレンド分析＆自動投稿ボット',
    description: 'Monitors daily trends, analyzes target audience sentiment, and automatically generates and schedules engaging social media posts.',
    descriptionEn: 'Monitors daily trends, analyzes target audience sentiment, and automatically generates and schedules engaging social media posts.',
    descriptionJa: '毎日のトレンドを監視・分析し、ターゲット層に刺さるSNS投稿を自動生成してスケジュール投稿を準備するエージェント。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'X Trend Auto-Poster Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-1',
          type: 'tool',
          position: { x: 50, y: 80 },
          data: {
            label: 'Google & Social Search',
            toolType: 'SerperDevTool',
            description: 'Search live Google & social trends for target keywords.',
          },
        },
        {
          id: 'tool-2',
          type: 'tool',
          position: { x: 50, y: 220 },
          data: {
            label: 'Brand Tone & Knowledge DB',
            toolType: 'TXTSearchTool',
            description: 'Reference brand guidelines and past viral post performance.',
          },
        },
        {
          id: 'agent-1',
          type: 'agent',
          position: { x: 340, y: 120 },
          data: {
            label: 'Trend Researcher',
            role: 'Viral Social Media Analyst',
            goal: 'Identify real-time trending tech/business topics and extract key sentiment patterns.',
            backstory: 'A data-driven growth marketer specializing in identifying viral social media hooks, emerging industry trends, and high-engagement topics on X/Twitter.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-2',
          type: 'agent',
          position: { x: 340, y: 380 },
          data: {
            label: 'Content Creator',
            role: 'Senior X Copywriter & Content Strategist',
            goal: 'Draft 3 highly engaging, 280-character posts tailored for maximum retweets and impressions.',
            backstory: 'An expert copywriter with a track record of crafting viral tech posts, engaging hooks, concise insights, and clear calls-to-action.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-1',
          type: 'task',
          position: { x: 680, y: 120 },
          data: {
            label: 'Research Live Trends',
            description: 'Search recent tech, AI, and business news from the last 24 hours. Analyze audience interest and identify top 3 viral discussion points.',
            expectedOutput: 'A structured summary of top 3 viral trends with engagement angles and target keywords.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-2',
          type: 'task',
          position: { x: 680, y: 380 },
          data: {
            label: 'Draft & Schedule Posts',
            description: 'Using trend insights and brand guidelines, craft 3 ready-to-post tweets with compelling hooks, strong value propositions, and relevant hashtags.',
            expectedOutput: '3 publication-ready tweet drafts formatted with line breaks, hashtags, and call-to-action.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'tool-1', target: 'agent-1' },
        { id: 'e2', source: 'tool-2', target: 'agent-2' },
        { id: 'e3', source: 'agent-1', target: 'task-1' },
        { id: 'e4', source: 'agent-2', target: 'task-2' },
        { id: 'e5', source: 'task-1', target: 'task-2' },
      ],
    },
  },
  {
    id: 'daily-news-blog-generator',
    title: '📰 Daily News Aggregator & Blog Generator',
    titleEn: '📰 Daily News Aggregator & Blog Generator',
    titleJa: '📰 業界ニュース自動収集＆翻訳ブログライター',
    description: 'Automatically scrapes daily industry news from global sources, translates them, and formats them into ready-to-publish SEO blog posts.',
    descriptionEn: 'Automatically scrapes daily industry news from global sources, translates them, and formats them into ready-to-publish SEO blog posts.',
    descriptionJa: '海外の最新ニュースサイトを毎日自動でスクレイピングし、日本語へ翻訳・要約してSEOに強いブログ記事として出力します。',
    price: 0,
    category: '1. Basic (順次処理)',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'Daily News Aggregator Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-3',
          type: 'tool',
          position: { x: 50, y: 100 },
          data: {
            label: 'Web News Scraper',
            toolType: 'ScrapeWebsiteTool',
            description: 'Extract raw text & headlines from foreign tech blogs.',
          },
        },
        {
          id: 'tool-4',
          type: 'tool',
          position: { x: 50, y: 240 },
          data: {
            label: 'Content Archive Inspector',
            toolType: 'DirectoryReadTool',
            description: 'Inspect local content archives to avoid redundant topics.',
          },
        },
        {
          id: 'agent-3',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'News Scraper',
            role: 'Global Tech News Researcher',
            goal: 'Scrape top tech blogs and extract breaking headlines, key statistics, and main quotes.',
            backstory: 'An automated news gathering specialist monitoring major international tech media 24/7 for breaking AI and software updates.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-4',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'SEO Writer',
            role: 'Bilingual Technical Editor & SEO Specialist',
            goal: 'Synthesize scraped foreign news into comprehensive, publication-ready Japanese SEO blog posts.',
            backstory: 'A seasoned tech journalist who crafts high-ranking Markdown articles with proper H2/H3 headings, meta descriptions, and clear summaries.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-3',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Crawl Breaking News',
            description: 'Scrape target tech news URLs, extract key headlines, publication dates, core announcements, and quote references.',
            expectedOutput: 'A compiled news dossier containing main facts, numbers, and source links.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-4',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Generate SEO Blog Article',
            description: 'Translate and synthesize facts into a 1,000-word Japanese SEO blog post with catchy titles, H2/H3 subheadings, TL;DR bullet points, and key takeaways.',
            expectedOutput: 'A publication-ready Japanese Markdown blog article complete with Meta Description and tags.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e6', source: 'tool-3', target: 'agent-3' },
        { id: 'e7', source: 'tool-4', target: 'agent-4' },
        { id: 'e8', source: 'agent-3', target: 'task-3' },
        { id: 'e9', source: 'agent-4', target: 'task-4' },
        { id: 'e10', source: 'task-3', target: 'task-4' },
      ],
    },
  },
  {
    id: 'competitor-price-monitor',
    title: '🔍 Competitor Price & Product Monitor',
    titleEn: '🔍 Competitor Price & Product Monitor',
    titleJa: '🔍 競合サイト価格＆新着商品モニター',
    description: 'Periodically checks competitor websites for pricing changes or new product launches and generates alert reports.',
    descriptionEn: 'Periodically checks competitor websites for pricing changes or new product launches and generates alert reports.',
    descriptionJa: '定期的に競合他社のウェブサイトを巡回し、価格の変動や新着商品の追加を検知してレポートを作成する監視ボット。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'Competitor Price Monitor Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-5',
          type: 'tool',
          position: { x: 50, y: 100 },
          data: {
            label: 'Competitor E-Commerce Scraper',
            toolType: 'ScrapeWebsiteTool',
            description: 'Fetch competitor product catalogs & pricing tables.',
          },
        },
        {
          id: 'tool-6',
          type: 'tool',
          position: { x: 50, y: 240 },
          data: {
            label: 'Historical Price Database',
            toolType: 'TXTSearchTool',
            description: 'Query past pricing baseline and historical product logs.',
          },
        },
        {
          id: 'agent-5',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Web Monitor',
            role: 'Competitive Intelligence Crawler',
            goal: 'Periodically scan competitor product pages to extract prices, stock status, and product titles.',
            backstory: 'A high-precision web data extractor built to monitor e-commerce catalogs and capture pricing updates reliably.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-6',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Data Analyst',
            role: 'Pricing & Market Intelligence Analyst',
            goal: 'Detect price fluctuations against baseline metrics and produce actionable executive alert summaries.',
            backstory: 'A retail pricing strategist who analyzes competitor price moves, detects discount patterns, and flags strategic market shifts.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-5',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Scrape Competitor Catalog',
            description: 'Scrape target competitor e-commerce listings, extracting SKU names, current prices, original list prices, and stock availability.',
            expectedOutput: 'A structured data matrix of scraped products with titles, prices, and stock statuses.',
            outputFormat: 'json',
            asyncExecution: false,
          },
        },
        {
          id: 'task-6',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Analyze Price Deltas & Alert',
            description: 'Compare scraped prices against historical baseline data. Highlight price cuts, price hikes, or new product additions, and generate alert flags (HIGH/MEDIUM/LOW).',
            expectedOutput: 'An Executive Competitor Alert Memo detailing price changes, percentage shifts, and recommended strategic counter-actions.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e11', source: 'tool-5', target: 'agent-5' },
        { id: 'e12', source: 'tool-6', target: 'agent-6' },
        { id: 'e13', source: 'agent-5', target: 'task-5' },
        { id: 'e14', source: 'agent-6', target: 'task-6' },
        { id: 'e15', source: 'task-5', target: 'task-6' },
      ],
    },
  },
  {
    id: 'csv-data-validator',
    title: '📊 CSV Data Validator & Outreach Crew',
    titleEn: '📊 CSV Data Validator & Outreach Crew',
    titleJa: '📊 データ検証＆英語コンタクトリスト作成',
    description: 'Inspects CSV data for inconsistencies and automatically generates a validated English contact list for outreach.',
    descriptionEn: 'Inspects CSV data for inconsistencies and automatically generates a validated English contact list for outreach.',
    descriptionJa: 'インポートしたCSV等のファイルから宛先件数やデータの不整合を検査し、検証用に抽出した英語のコンタクトリストを自動生成します。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Data Validation & Outreach',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-csv',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'CSV File Analyzer',
            toolType: 'CSVSearchTool',
            description: 'Search and read contents of local CSV files for data extraction.',
          },
        },
        {
          id: 'agent-data-inspector',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Data Quality Inspector',
            role: 'Senior Data Quality Analyst',
            goal: 'Identify data inconsistencies, missing fields, and extract valid rows from the dataset.',
            backstory: 'A meticulous data quality inspector expert at finding anomalies, cleaning up messy datasets, and ensuring data integrity for enterprise systems.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-outreach',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Outreach Specialist',
            role: 'Multilingual Outreach Specialist',
            goal: 'Generate a professional English contact list and personalized outreach message templates.',
            backstory: 'An expert outreach specialist and copywriter who crafts highly engaging, professional, and personalized contact emails in English.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-verify',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Verify Destination Counts',
            description: 'Search through the provided CSV file to verify the total count of valid destination records. Find any missing or malformed data fields (e.g. invalid emails).',
            expectedOutput: 'A detailed validation report containing valid record counts, error logs, and a cleaned data subset.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-generate-list',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Generate English Contact List',
            description: 'Using the cleaned data subset from the validation report, generate a formal English contact list with personalized outreach message templates for each verified contact.',
            expectedOutput: 'A Markdown table containing the contact list along with customized English message templates.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-csv1', source: 'tool-csv', target: 'agent-data-inspector' },
        { id: 'e-csv2', source: 'agent-data-inspector', target: 'task-verify' },
        { id: 'e-csv3', source: 'agent-outreach', target: 'task-generate-list' },
        { id: 'e-csv4', source: 'task-verify', target: 'task-generate-list' },
      ],
    },
  },
  {
    id: 'github-repo-analyzer',
    title: '💻 GitHub Repo Analyzer & Doc Gen',
    titleEn: '💻 GitHub Repo Analyzer & Doc Gen',
    titleJa: '💻 GitHubコードレビュー＆ドキュメント生成',
    description: 'Analyzes GitHub repositories for code quality and automatically drafts comprehensive technical documentation.',
    descriptionEn: 'Analyzes GitHub repositories for code quality and automatically drafts comprehensive technical documentation.',
    descriptionJa: '指定したGitHubリポジトリを読み込んでコード品質をレビューし、分かりやすいREADMEや技術解説ドキュメントを生成します。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'GitHub Repo Analyzer',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-github',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'GitHub Code Search',
            toolType: 'GithubSearchTool',
            description: 'Search and read source code from GitHub repositories.',
          },
        },
        {
          id: 'agent-code-reviewer',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Senior Code Reviewer',
            role: 'Principal Software Engineer',
            goal: 'Review the GitHub repository code structure and identify potential improvements, bugs, or architectural flaws.',
            backstory: 'A veteran software engineer with 15+ years of experience in system architecture, design patterns, and enforcing code quality standards across large codebases.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-tech-writer',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Technical Writer',
            role: 'Senior Technical Writer',
            goal: 'Draft comprehensive and developer-friendly technical documentation based on the code analysis.',
            backstory: 'A skilled technical writer capable of translating complex code architectures and logic into clear, engaging, and easy-to-read developer documentation.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-analyze-repo',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Analyze Repo Structure',
            description: 'Search through the target GitHub repository. Analyze the file structure, core dependencies, and review the main application logic for code quality and potential anti-patterns.',
            expectedOutput: 'A comprehensive technical code review report highlighting strengths, weaknesses, and architectural suggestions.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-draft-docs',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Draft Documentation',
            description: 'Take the technical code review report and draft a clear, well-structured README.md file and technical architecture document. Make sure to explain the core functionalities simply.',
            expectedOutput: 'A polished README.md file and an accompanying technical overview document in Markdown format.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-gh1', source: 'tool-github', target: 'agent-code-reviewer' },
        { id: 'e-gh2', source: 'agent-code-reviewer', target: 'task-analyze-repo' },
        { id: 'e-gh3', source: 'agent-tech-writer', target: 'task-draft-docs' },
        { id: 'e-gh4', source: 'task-analyze-repo', target: 'task-draft-docs' },
      ],
    },
  },
  {
    id: 'youtube-to-blog',
    title: '▶️ YouTube to Blog Post Converter',
    titleEn: '▶️ YouTube to Blog Post Converter',
    titleJa: '▶️ YouTube動画からSEOブログ自動生成',
    description: 'Extracts content from YouTube videos and restructures it into fully formatted, SEO-optimized blog articles.',
    descriptionEn: 'Extracts content from YouTube videos and restructures it into fully formatted, SEO-optimized blog articles.',
    descriptionJa: 'YouTube動画のURLから内容を抽出し、要約だけでなくSEOに最適化された見出し付きのブログ記事に再構築します。',
    price: 0,
    category: '1. Basic (順次処理)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'YouTube Content Repurposer',
        process: 'sequential',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-youtube',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'YouTube Transcript Extractor',
            toolType: 'YoutubeVideoSearchTool',
            description: 'Extract transcripts and metadata from YouTube videos.',
          },
        },
        {
          id: 'agent-video-extractor',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Video Content Extractor',
            role: 'Expert Media Analyst',
            goal: 'Extract the main ideas, quotes, and narrative structure from a given YouTube video transcript.',
            backstory: 'An expert media analyst capable of breaking down long-form video content into core concepts, key takeaways, and actionable insights.',
            model: 'gpt-5.6-luna',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-seo-writer',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'SEO Content Writer',
            role: 'Senior SEO Blog Writer',
            goal: 'Transform video summaries into comprehensive, SEO-optimized blog posts that rank high on Google.',
            backstory: 'A seasoned SEO blog writer who specializes in creating engaging, high-ranking content optimized for search engines, with perfect formatting and readability.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-summarize-video',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Summarize Video Concepts',
            description: 'Analyze the transcript of the provided YouTube video URL. Extract the primary thesis, 3-5 main supporting arguments, and any notable quotes.',
            expectedOutput: 'A structured summary of the video content, organized logically by main themes and key takeaways.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-write-blog',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Write Blog Article',
            description: 'Using the extracted video concepts, write a compelling, 1500-word SEO-optimized blog post. Include a catchy H1 title, well-structured H2/H3 headings, and an introductory hook.',
            expectedOutput: 'A fully formatted Markdown blog post ready for publishing, complete with SEO meta title and description.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-yt1', source: 'tool-youtube', target: 'agent-video-extractor' },
        { id: 'e-yt2', source: 'agent-video-extractor', target: 'task-summarize-video' },
        { id: 'e-yt3', source: 'agent-seo-writer', target: 'task-write-blog' },
        { id: 'e-yt4', source: 'task-summarize-video', target: 'task-write-blog' },
      ],
    },
  },
  {
    id: 'parallel-web-research',
    title: '🌐 Parallel Web Research',
    titleEn: '🌐 Parallel Web Research',
    titleJa: '🌐 Web並行リサーチ＆レポート (非同期)',
    description: 'Searches multiple sources concurrently and synthesizes findings into a single report.',
    descriptionEn: 'Searches multiple sources concurrently and synthesizes findings into a single report.',
    descriptionJa: '複数のタスクを非同期（並行）で実行し、Webリサーチを高速化。最後に結果を統合します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 4, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Parallel Research Crew',
        process: 'sequential',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-search',
          type: 'tool',
          position: { x: 50, y: 220 },
          data: {
            label: 'Web Search Tool',
            toolType: 'SerperDevTool',
            description: 'Search the web for real-time information.',
          },
        },
        {
          id: 'agent-researcher',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Web Researcher',
            role: 'Expert Web Researcher',
            goal: 'Find accurate and up-to-date information on the web.',
            backstory: 'An expert researcher capable of finding anything on the web.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-writer',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Report Writer',
            role: 'Senior Technical Writer',
            goal: 'Synthesize research findings into a comprehensive report.',
            backstory: 'A technical writer who excels at combining multiple sources into cohesive reports.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-research-1',
          type: 'task',
          position: { x: 680, y: 50 },
          data: {
            label: 'Research Topic A (Async)',
            description: 'Search for the latest news on Artificial Intelligence.',
            expectedOutput: 'Summary of recent AI news.',
            asyncExecution: true,
          },
        },
        {
          id: 'task-research-2',
          type: 'task',
          position: { x: 680, y: 180 },
          data: {
            label: 'Research Topic B (Async)',
            description: 'Search for the latest news on Quantum Computing.',
            expectedOutput: 'Summary of recent Quantum Computing news.',
            asyncExecution: true,
          },
        },
        {
          id: 'task-research-3',
          type: 'task',
          position: { x: 680, y: 310 },
          data: {
            label: 'Research Topic C (Async)',
            description: 'Search for the latest news on Space Exploration.',
            expectedOutput: 'Summary of recent Space Exploration news.',
            asyncExecution: true,
          },
        },
        {
          id: 'task-synthesis',
          type: 'task',
          position: { x: 960, y: 400 },
          data: {
            label: 'Synthesize Report',
            description: 'Combine the findings from all three research tasks into a single comprehensive report.',
            expectedOutput: 'A unified Markdown report.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-r1', source: 'tool-search', target: 'agent-researcher' },
        { id: 'e-r2', source: 'agent-researcher', target: 'task-research-1' },
        { id: 'e-r3', source: 'agent-researcher', target: 'task-research-2' },
        { id: 'e-r4', source: 'agent-researcher', target: 'task-research-3' },
        { id: 'e-r5', source: 'agent-writer', target: 'task-synthesis' },
        { id: 'e-r6', source: 'task-research-1', target: 'task-synthesis' },
        { id: 'e-r7', source: 'task-research-2', target: 'task-synthesis' },
        { id: 'e-r8', source: 'task-research-3', target: 'task-synthesis' },
      ],
    },
  },
  {
    id: 'hierarchical-software-team',
    title: '💻 Hierarchical Software Team',
    titleEn: '💻 Hierarchical Software Team',
    titleJa: '💻 階層型ソフトウェア開発チーム (Manager AI)',
    description: 'A Manager AI oversees a Senior Developer and a QA Engineer to build robust software.',
    descriptionEn: 'A Manager AI oversees a Senior Developer and a QA Engineer to build robust software.',
    descriptionJa: 'マネージャーAIがタスクを分割し、開発者とQAエンジニアに委任してソフトウェアを開発します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 0 },
    graphData: {
      crewConfig: {
        name: 'Hierarchical Software Team',
        process: 'hierarchical',
        managerLlm: 'gpt-5.6-terra',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'agent-dev',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Senior Developer',
            role: 'Senior Full Stack Developer',
            goal: 'Write clean, scalable, and efficient code based on requirements.',
            backstory: 'A senior developer with 10 years of experience in React and Node.js.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-qa',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'QA Engineer',
            role: 'Quality Assurance Engineer',
            goal: 'Test code thoroughly and find any edge cases or bugs.',
            backstory: 'A meticulous QA engineer who ensures zero defects in production.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-dev',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Develop Feature',
            description: 'Develop a fully functional login form component with validation in React and TypeScript.',
            expectedOutput: 'Complete, clean source code for the login form component.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-qa',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'QA and Security Review',
            description: 'Inspect the developed login form component, write unit tests, and verify edge cases and input validation.',
            expectedOutput: 'QA test report with test suite code and verification status.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-h1', source: 'agent-dev', target: 'task-dev' },
        { id: 'e-h2', source: 'agent-qa', target: 'task-qa' },
        { id: 'e-h3', source: 'task-dev', target: 'task-qa' }
      ],
    },
  },
  {
    id: 'hierarchical-marketing-campaign',
    title: '📣 Hierarchical Marketing Campaign',
    titleEn: '📣 Hierarchical Marketing Campaign',
    titleJa: '📣 階層型マーケティング・キャンペーン (Manager AI)',
    description: 'A Manager AI orchestrates a Market Analyst and a Copywriter to create a cohesive campaign.',
    descriptionEn: 'A Manager AI orchestrates a Market Analyst and a Copywriter to create a cohesive campaign.',
    descriptionJa: 'マネージャーAIが市場アナリストとコピーライターを統括し、一貫性のあるキャンペーンを構築します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Marketing Campaign Crew',
        process: 'hierarchical',
        managerLlm: 'gpt-5.6-terra',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-market',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'Web Search',
            toolType: 'SerperDevTool',
            description: 'Search for market trends and competitors.',
          },
        },
        {
          id: 'agent-analyst',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Market Analyst',
            role: 'Senior Market Analyst',
            goal: 'Analyze market trends and identify target audience segments.',
            backstory: 'An expert in reading market trends and finding lucrative niches.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-copywriter',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Copywriter',
            role: 'Direct Response Copywriter',
            goal: 'Create high-converting ad copy based on market analysis.',
            backstory: 'A legendary copywriter known for writing ads that generate millions in revenue.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-analyze',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Analyze Target Market',
            description: 'Research the current market for eco-friendly sneakers.',
            expectedOutput: 'A detailed market analysis report.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-copy',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Write Ad Copy',
            description: 'Write 3 Facebook ad variations targeting the audience identified in the market analysis.',
            expectedOutput: '3 polished Facebook ad copies.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-m1', source: 'tool-market', target: 'agent-analyst' },
        { id: 'e-m2', source: 'agent-analyst', target: 'task-analyze' },
        { id: 'e-m3', source: 'agent-copywriter', target: 'task-copy' },
        { id: 'e-m4', source: 'task-analyze', target: 'task-copy' }
      ],
    },
  },
  {
    id: 'repository-red-team-audit',
    title: '🛡️ Repository Red-Team Audit',
    titleEn: '🛡️ Repository Red-Team Audit',
    titleJa: '🛡️ リポジトリ・レッドチーム監査',
    description: 'Runs architecture, security, reliability, adversarial, and cost reviews before producing a release decision.',
    descriptionEn: 'Runs architecture, security, reliability, adversarial, and cost reviews before producing a release decision.',
    descriptionJa: '設計・セキュリティ・信頼性・攻撃シミュレーション・コストを分担して監査し、最終リリース判定を作成します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 6, tasks: 7, tools: 0 },
    graphData: {
      crewConfig: {
        name: 'Repository Red-Team Audit Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'rt-agent-architecture',
          type: 'agent',
          position: { x: 80, y: 80 },
          data: {
            label: 'Architecture Inspector',
            role: 'Software Architecture Inspector',
            goal: 'Reconstruct and evaluate the architecture of {repository_path}.',
            backstory: 'A principal architect who maps unfamiliar systems and identifies risky coupling, unclear boundaries, and maintainability issues.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-security',
          type: 'agent',
          position: { x: 80, y: 260 },
          data: {
            label: 'Security Red Teamer',
            role: 'Application Security Red Teamer',
            goal: 'Identify exploitable security weaknesses without modifying the repository.',
            backstory: 'An application security specialist experienced in threat modeling, dependency risk, secrets exposure, and abuse-case analysis.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-reliability',
          type: 'agent',
          position: { x: 80, y: 440 },
          data: {
            label: 'Reliability Engineer',
            role: 'Site Reliability Engineer',
            goal: 'Find failure modes, operational gaps, and recovery risks.',
            backstory: 'A production reliability engineer focused on graceful degradation, observability, concurrency, and disaster recovery.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-adversarial',
          type: 'agent',
          position: { x: 80, y: 620 },
          data: {
            label: 'Adversarial Tester',
            role: 'Adversarial Test Designer',
            goal: 'Design safe, non-destructive simulations for the combined audit findings.',
            backstory: 'A test strategist who turns architectural, security, and reliability concerns into reproducible negative test scenarios.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-cost',
          type: 'agent',
          position: { x: 80, y: 800 },
          data: {
            label: 'Cost Auditor',
            role: 'Cloud Cost Auditor',
            goal: 'Estimate operational cost drivers and identify avoidable spend.',
            backstory: 'A FinOps specialist who evaluates infrastructure choices, scaling assumptions, and third-party service costs.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-release',
          type: 'agent',
          position: { x: 80, y: 980 },
          data: {
            label: 'Release Judge',
            role: 'Independent Release Judge',
            goal: 'Issue an evidence-based release recommendation from all audit outputs.',
            backstory: 'An independent engineering leader who prioritizes findings, records uncertainty, and defines explicit release gates.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-task-reconstruct',
          type: 'task',
          position: { x: 430, y: 80 },
          data: {
            label: 'Graph Reconstruction',
            description: 'Inspect {repository_path} in read-only mode. Map entrypoints, modules, data flows, external services, trust boundaries, and deployment assumptions.',
            expectedOutput: 'A Markdown architecture map with components, boundaries, data flows, assumptions, and evidence references.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-architecture',
          type: 'task',
          position: { x: 760, y: 80 },
          data: {
            label: 'Architecture Audit',
            description: 'Using the reconstructed graph, assess coupling, ownership boundaries, maintainability, scalability, and unsafe architectural assumptions.',
            expectedOutput: 'A prioritized architecture audit with severity, evidence, impact, and remediation for every finding.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-security',
          type: 'task',
          position: { x: 760, y: 270 },
          data: {
            label: 'Security Audit',
            description: 'Perform a non-destructive security review of {repository_path}. Cover authentication, authorization, input handling, secrets, dependencies, data exposure, and abuse cases.',
            expectedOutput: 'A prioritized security audit with threat scenario, evidence, likelihood, impact, and remediation for each finding.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-reliability',
          type: 'task',
          position: { x: 760, y: 460 },
          data: {
            label: 'Reliability Audit',
            description: 'Review failure handling, retries, timeouts, idempotency, concurrency, observability, deployment safety, and recovery procedures.',
            expectedOutput: 'A reliability risk register with failure mode, trigger, user impact, detectability, and mitigation.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-adversarial',
          type: 'task',
          position: { x: 1080, y: 360 },
          data: {
            label: 'Adversarial Simulation',
            description: 'Synthesize the architecture, security, and reliability audits into safe test scenarios. Do not execute destructive actions or alter external systems.',
            expectedOutput: 'A non-destructive adversarial test plan with preconditions, steps, expected signals, stop conditions, and success criteria.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-cost',
          type: 'task',
          position: { x: 760, y: 720 },
          data: {
            label: 'Cost Analysis',
            description: 'Analyze likely compute, storage, network, model, and managed-service costs. State assumptions and identify the largest cost sensitivities.',
            expectedOutput: 'A cost analysis with assumptions, primary drivers, optimization options, and uncertainty ranges.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-release',
          type: 'task',
          position: { x: 1400, y: 500 },
          data: {
            label: 'Release Report',
            description: 'Combine every audit and simulation result. Deduplicate findings, assign owners and release gates, and produce a final go, conditional-go, or no-go recommendation for {output_directory}.',
            expectedOutput: 'A structured JSON release report with decision, blockers, prioritized findings, owners, release gates, and residual risks.',
            outputFormat: 'json',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'rt-e-a-reconstruct', source: 'rt-agent-architecture', target: 'rt-task-reconstruct' },
        { id: 'rt-e-a-architecture', source: 'rt-agent-architecture', target: 'rt-task-architecture' },
        { id: 'rt-e-a-security', source: 'rt-agent-security', target: 'rt-task-security' },
        { id: 'rt-e-a-reliability', source: 'rt-agent-reliability', target: 'rt-task-reliability' },
        { id: 'rt-e-a-adversarial', source: 'rt-agent-adversarial', target: 'rt-task-adversarial' },
        { id: 'rt-e-a-cost', source: 'rt-agent-cost', target: 'rt-task-cost' },
        { id: 'rt-e-a-release', source: 'rt-agent-release', target: 'rt-task-release' },
        { id: 'rt-e-reconstruct-architecture', source: 'rt-task-reconstruct', target: 'rt-task-architecture' },
        { id: 'rt-e-reconstruct-security', source: 'rt-task-reconstruct', target: 'rt-task-security' },
        { id: 'rt-e-reconstruct-reliability', source: 'rt-task-reconstruct', target: 'rt-task-reliability' },
        { id: 'rt-e-architecture-adversarial', source: 'rt-task-architecture', target: 'rt-task-adversarial' },
        { id: 'rt-e-security-adversarial', source: 'rt-task-security', target: 'rt-task-adversarial' },
        { id: 'rt-e-reliability-adversarial', source: 'rt-task-reliability', target: 'rt-task-adversarial' },
        { id: 'rt-e-architecture-release', source: 'rt-task-architecture', target: 'rt-task-release' },
        { id: 'rt-e-security-release', source: 'rt-task-security', target: 'rt-task-release' },
        { id: 'rt-e-reliability-release', source: 'rt-task-reliability', target: 'rt-task-release' },
        { id: 'rt-e-adversarial-release', source: 'rt-task-adversarial', target: 'rt-task-release' },
        { id: 'rt-e-cost-release', source: 'rt-task-cost', target: 'rt-task-release' },
      ],
    },
  },
];

type TemplateGuide = Pick<
  WorkflowTemplate,
  | 'useCase' | 'useCaseEn' | 'useCaseJa'
  | 'codePattern' | 'codePatternEn' | 'codePatternJa'
  | 'difficulty' | 'bestForEn' | 'bestForJa'
  | 'codeGuideEn' | 'codeGuideJa'
  | 'prerequisitesEn' | 'prerequisitesJa'
  | 'deliverablesEn' | 'deliverablesJa'
>;

const TEMPLATE_GUIDES: Record<string, TemplateGuide> = {
  'x-trend-auto-poster': {
    useCase: 'SOCIAL', useCaseEn: 'Social Media', useCaseJa: 'SNS運用',
    codePattern: 'SEQUENTIAL', codePatternEn: 'Sequential pipeline', codePatternJa: '順次パイプライン', difficulty: 'STARTER',
    bestForEn: 'Teams that want a repeatable research-to-draft workflow for X posts.',
    bestForJa: 'X投稿のトレンド調査から下書き作成までを定型化したい運用チーム向け。',
    codeGuideEn: 'Research task feeds one writing task through CrewAI context. Two tools are attached to separate specialist agents.',
    codeGuideJa: '調査Taskの結果をcontext経由で執筆Taskへ渡す2段構成。各Agentへ検索・ブランド資料Toolを分担します。',
    prerequisitesEn: ['OpenAI API key', 'Serper API key', 'Brand guideline TXT'],
    prerequisitesJa: ['OpenAI APIキー', 'Serper APIキー', 'ブランドガイドのTXT'],
    deliverablesEn: ['Trend brief', '3 post drafts'], deliverablesJa: ['トレンド要約', '投稿案3本'],
  },
  'daily-news-blog-generator': {
    useCase: 'CONTENT', useCaseEn: 'Content Production', useCaseJa: 'コンテンツ制作',
    codePattern: 'SEQUENTIAL', codePatternEn: 'Sequential pipeline', codePatternJa: '順次パイプライン', difficulty: 'STARTER',
    bestForEn: 'Editors turning daily source material into localized SEO articles.',
    bestForJa: '海外ニュースを収集し、日本語SEO記事へ定期変換したい編集者向け。',
    codeGuideEn: 'A collection agent gathers source pages, then a writer receives the research as task context and produces the article.',
    codeGuideJa: '収集Agentが情報源をまとめ、そのTask出力をcontextとしてライターへ渡す直列構成です。',
    prerequisitesEn: ['OpenAI API key', 'Target news URLs', 'Output directory'],
    prerequisitesJa: ['OpenAI APIキー', '対象ニュースURL', '出力ディレクトリ'],
    deliverablesEn: ['Source digest', 'SEO blog draft'], deliverablesJa: ['情報源ダイジェスト', 'SEOブログ下書き'],
  },
  'competitor-price-monitor': {
    useCase: 'RESEARCH', useCaseEn: 'Competitive Intelligence', useCaseJa: '競合調査',
    codePattern: 'SEQUENTIAL', codePatternEn: 'Sequential + validated JSON', codePatternJa: '順次処理＋検証済みJSON', difficulty: 'INTERMEDIATE',
    bestForEn: 'Commerce teams comparing competitor catalog and price changes.',
    bestForJa: '競合商品の価格・在庫変化を比較したいEC／事業企画チーム向け。',
    codeGuideEn: 'Scraping produces a Pydantic-validated product matrix before the analysis task creates prioritized alerts.',
    codeGuideJa: 'スクレイピング結果をPydantic検証済みの商品マトリクスにし、後続Taskが変化と優先度を判定します。',
    prerequisitesEn: ['OpenAI API key', 'Competitor URLs', 'Historical baseline TXT'],
    prerequisitesJa: ['OpenAI APIキー', '競合サイトURL', '過去価格のTXT'],
    deliverablesEn: ['Validated product matrix', 'Change alert report'], deliverablesJa: ['検証済み商品データ', '価格変動アラート'],
  },
  'csv-data-validator': {
    useCase: 'DATA', useCaseEn: 'Data Operations', useCaseJa: 'データ業務',
    codePattern: 'SEQUENTIAL', codePatternEn: 'Sequential pipeline', codePatternJa: '順次パイプライン', difficulty: 'STARTER',
    bestForEn: 'Operations teams cleaning contact data before outreach.',
    bestForJa: '営業リストを配信前に検査・整形したいデータ／営業業務向け。',
    codeGuideEn: 'A CSV validation task creates a clean subset that becomes context for the outreach-generation task.',
    codeGuideJa: 'CSV検証Taskがクリーンなデータを作り、その結果を営業文面生成Taskへcontextとして渡します。',
    prerequisitesEn: ['OpenAI API key', 'Input CSV'], prerequisitesJa: ['OpenAI APIキー', '入力CSV'],
    deliverablesEn: ['Validation report', 'Clean contact list', 'Outreach drafts'], deliverablesJa: ['検証レポート', '整形済み連絡先', '営業文面案'],
  },
  'github-repo-analyzer': {
    useCase: 'ENGINEERING', useCaseEn: 'Engineering', useCaseJa: '開発・技術文書',
    codePattern: 'SEQUENTIAL', codePatternEn: 'Sequential pipeline', codePatternJa: '順次パイプライン', difficulty: 'INTERMEDIATE',
    bestForEn: 'Developers onboarding to a repository or refreshing technical documentation.',
    bestForJa: '既存リポジトリの把握や技術ドキュメント更新を効率化したい開発者向け。',
    codeGuideEn: 'Repository analysis runs first; its findings are injected into a dedicated documentation task.',
    codeGuideJa: 'リポジトリ解析を先に行い、その結果を専任の文書化Taskへ注入する2段構成です。',
    prerequisitesEn: ['OpenAI API key', 'GitHub token', 'Repository access'],
    prerequisitesJa: ['OpenAI APIキー', 'GitHubトークン', 'リポジトリ権限'],
    deliverablesEn: ['Architecture summary', 'README/documentation draft'], deliverablesJa: ['構成要約', 'README／技術文書案'],
  },
  'youtube-to-blog': {
    useCase: 'CONTENT', useCaseEn: 'Content Repurposing', useCaseJa: 'コンテンツ再利用',
    codePattern: 'SEQUENTIAL', codePatternEn: 'Sequential pipeline', codePatternJa: '順次パイプライン', difficulty: 'STARTER',
    bestForEn: 'Creators converting long-form videos into searchable written content.',
    bestForJa: '動画を検索流入向けの記事へ再利用したいクリエイター／編集者向け。',
    codeGuideEn: 'Video retrieval and summarization complete before the writing agent receives the structured notes.',
    codeGuideJa: '動画検索・要約を完了後、その整理結果をライターAgentへ渡して記事化します。',
    prerequisitesEn: ['OpenAI API key', 'YouTube URL or query'], prerequisitesJa: ['OpenAI APIキー', 'YouTube URLまたは検索語'],
    deliverablesEn: ['Video outline', 'SEO blog draft'], deliverablesJa: ['動画構成要約', 'SEOブログ下書き'],
  },
  'parallel-web-research': {
    useCase: 'RESEARCH', useCaseEn: 'Web Research', useCaseJa: 'Webリサーチ',
    codePattern: 'PARALLEL', codePatternEn: 'Parallel fan-out / synthesis', codePatternJa: '並列分岐／統合', difficulty: 'INTERMEDIATE',
    bestForEn: 'Analysts who need independent research streams merged into one report.',
    bestForJa: '複数観点の調査を同時に進め、最後に統合したいリサーチ業務向け。',
    codeGuideEn: 'Independent async tasks fan out from specialist agents; a final synthesis task waits for both contexts.',
    codeGuideJa: '専門Agentの非同期Taskを並列実行し、最終統合Taskが両方のcontextを待つfan-out構成です。',
    prerequisitesEn: ['OpenAI API key', 'Serper API key', 'Research topic'],
    prerequisitesJa: ['OpenAI APIキー', 'Serper APIキー', '調査テーマ'],
    deliverablesEn: ['Independent findings', 'Synthesized research report'], deliverablesJa: ['観点別調査結果', '統合リサーチレポート'],
  },
  'hierarchical-software-team': {
    useCase: 'ENGINEERING', useCaseEn: 'Software Delivery', useCaseJa: 'ソフトウェア開発',
    codePattern: 'HIERARCHICAL', codePatternEn: 'Hierarchical manager', codePatternJa: '階層型マネージャー', difficulty: 'ADVANCED',
    bestForEn: 'Teams experimenting with manager-led delegation across engineering roles.',
    bestForJa: 'マネージャーLLMによる開発ロールへの動的委任を試したいチーム向け。',
    codeGuideEn: 'CrewAI Process.hierarchical uses a manager LLM to allocate unassigned work across engineering agents.',
    codeGuideJa: 'CrewAIのProcess.hierarchicalで、manager_llmが未割当Taskを各開発Agentへ動的に委任します。',
    prerequisitesEn: ['OpenAI API key', 'Clear product requirements'], prerequisitesJa: ['OpenAI APIキー', '明確な要件定義'],
    deliverablesEn: ['Implementation plan', 'Reviewed code proposal'], deliverablesJa: ['実装計画', 'レビュー済みコード案'],
  },
  'hierarchical-marketing-campaign': {
    useCase: 'MARKETING', useCaseEn: 'Campaign Planning', useCaseJa: 'マーケ施策',
    codePattern: 'HIERARCHICAL', codePatternEn: 'Hierarchical manager', codePatternJa: '階層型マネージャー', difficulty: 'ADVANCED',
    bestForEn: 'Marketing teams coordinating research and creative work under one campaign manager.',
    bestForJa: '調査とクリエイティブを統括マネージャーの下で連携させたいマーケチーム向け。',
    codeGuideEn: 'A manager LLM delegates research and campaign creation while shared search tooling grounds decisions.',
    codeGuideJa: 'manager_llmが市場調査と施策作成を委任し、共有検索Toolで意思決定を最新情報へ接地します。',
    prerequisitesEn: ['OpenAI API key', 'Serper API key', 'Campaign brief'], prerequisitesJa: ['OpenAI APIキー', 'Serper APIキー', 'キャンペーン概要'],
    deliverablesEn: ['Market insight brief', 'Integrated campaign plan'], deliverablesJa: ['市場インサイト', '統合キャンペーン計画'],
  },
  'repository-red-team-audit': {
    useCase: 'SECURITY', useCaseEn: 'Security & Release', useCaseJa: 'セキュリティ・リリース',
    codePattern: 'DAG', codePatternEn: 'Multi-stage audit DAG', codePatternJa: '多段監査DAG', difficulty: 'ADVANCED',
    bestForEn: 'Engineering leaders preparing an evidence-based release readiness review.',
    bestForJa: 'リリース前に設計・安全性・信頼性・コストを横断評価したい責任者向け。',
    codeGuideEn: 'Six specialists feed a dependency DAG. The release judge waits for five audit branches and emits validated JSON.',
    codeGuideJa: '6専門Agentの監査結果を依存DAGで集約し、最終判定Taskが5系統を待って検証済みJSONを出力します。',
    prerequisitesEn: ['OpenAI API key', 'Local repository path', 'Sandboxed read-only runtime'],
    prerequisitesJa: ['OpenAI APIキー', 'ローカルのリポジトリパス', '読み取り専用サンドボックス'],
    deliverablesEn: ['Risk registers', 'Adversarial test plan', 'Validated release decision JSON'],
    deliverablesJa: ['各種リスク台帳', '攻撃的テスト計画', '検証済みリリース判定JSON'],
  },
};

interface GraphRefinement {
  template?: Partial<Pick<WorkflowTemplate, 'title' | 'titleEn' | 'titleJa' | 'description' | 'descriptionEn' | 'descriptionJa'>>;
  crewName?: string;
  nodeData: Record<string, Record<string, unknown>>;
  additionalNodes?: CustomNode[];
  additionalEdges?: Edge[];
}

const TEMPLATE_GRAPH_REFINEMENTS: Record<string, GraphRefinement> = {
  'x-trend-auto-poster': {
    template: {
      title: '📱 X Trend-to-Draft Content Planner', titleEn: '📱 X Trend-to-Draft Content Planner', titleJa: '📱 Xトレンド調査＆投稿作成プランナー',
      description: 'Researches current topics for a defined audience and creates evidence-aware X post drafts for human review.',
      descriptionEn: 'Researches current topics for a defined audience and creates evidence-aware X post drafts for human review.',
      descriptionJa: '指定業界の最新話題を調査し、ブランドルールに沿ったX投稿案を人間の確認用に作成します。',
    },
    crewName: 'X Content Planning Crew',
    nodeData: {
      'agent-1': { role: 'Evidence-First Social Trend Researcher', goal: 'Find timely, verifiable topics in {industry} that matter to {target_audience}, recording source URLs and publication dates.', backstory: 'A cautious social researcher who distinguishes confirmed facts from speculation and rejects stale or unsourced claims.' },
      'agent-2': { role: 'Brand-Safe X Content Editor', goal: 'Turn verified findings into distinct X drafts that follow {brand_voice} and remain within the requested character limit.', backstory: 'A senior social editor who optimizes clarity and relevance without fabricating urgency, metrics, or endorsements.' },
      'task-1': { label: 'Build Evidence-Backed Trend Brief', description: 'Research {industry} developments relevant to {target_audience}. Select up to 3 topics. For each, record the source URL, publication date, verified facts, why it matters, and reputational risk. Do not treat search snippets as evidence.', expectedOutput: 'A Markdown trend brief with up to 3 topics, dated source links, verified facts, audience relevance, and risk notes.' },
      'task-2': { label: 'Draft Posts for Human Review', description: 'Using the trend brief and brand reference, create 3 materially different X post drafts in {brand_voice}. Keep each within 280 characters, distinguish facts from opinion, and include a source link where appropriate. Do not publish or claim that scheduling occurred.', expectedOutput: 'Three review-ready X drafts with character counts, recommended posting rationale, source links, and a short factual-risk checklist.' },
      'tool-1': { description: 'Search recent web sources for the configured industry and audience; results still require source verification.' },
      'tool-2': { description: 'Search local brand voice, prohibited-claims, and approval guidelines.' },
    },
  },
  'daily-news-blog-generator': {
    template: {
      title: '📰 Source-Grounded News Brief & Blog Draft', titleEn: '📰 Source-Grounded News Brief & Blog Draft', titleJa: '📰 出典付きニュース要約＆ブログ下書き',
      description: 'Builds a dated source dossier and converts it into a localized article draft with explicit citations and uncertainty notes.',
      descriptionEn: 'Builds a dated source dossier and converts it into a localized article draft with explicit citations and uncertainty notes.',
      descriptionJa: '指定したニュースソースから日付付き調査メモを作成し、引用と不確実性を明記した記事下書きへ変換します。',
    },
    crewName: 'Grounded News Editorial Crew',
    nodeData: {
      'agent-3': { role: 'Source Verification Researcher', goal: 'Extract and cross-check dated facts from {source_urls} without inventing quotes or relying on headlines alone.', backstory: 'A newsroom researcher trained to preserve links, dates, attribution, and unresolved contradictions.' },
      'agent-4': { role: 'Localized SEO Editor', goal: 'Create an accurate {target_language} article for {target_reader} while preserving attribution and editorial nuance.', backstory: 'A bilingual editor who prioritizes reader value and factual fidelity over keyword stuffing.' },
      'task-3': { label: 'Create Verified Source Dossier', description: 'Read {source_urls}. Capture title, publisher, publication date, canonical URL, primary facts, attributed quotes, and disagreements between sources. Compare the local archive for duplicate coverage.', expectedOutput: 'A dated source dossier in Markdown with canonical links, attributed facts, contradictions, and duplicate-topic notes.', outputFormat: 'text' },
      'task-4': { label: 'Write Localized Article Draft', description: 'Write a {target_language} article for {target_reader} using only the dossier. Include a concise title, meta description, H2/H3 structure, inline source links, key takeaways, and an editorial note for claims needing manual verification.', expectedOutput: 'A publication-review-ready Markdown article with citations, meta description, suggested slug, and manual verification checklist.' },
    },
  },
  'competitor-price-monitor': {
    template: {
      title: '🔍 Competitor Catalog Snapshot & Price Delta Review', titleEn: '🔍 Competitor Catalog Snapshot & Price Delta Review', titleJa: '🔍 競合カタログ取得＆価格差分レビュー',
      description: 'Captures a point-in-time catalog snapshot and compares normalized products against a supplied baseline.',
      descriptionEn: 'Captures a point-in-time catalog snapshot and compares normalized products against a supplied baseline.',
      descriptionJa: '競合カタログのスナップショットを取得し、支給済みの基準データと正規化比較します。',
    },
    crewName: 'Competitor Catalog Review Crew',
    nodeData: {
      'agent-5': { role: 'Catalog Evidence Collector', goal: 'Capture reproducible product facts from {competitor_urls}, including timestamp, currency, unit, availability, and source URL.', backstory: 'A methodical commerce researcher who avoids guessing variants, taxes, shipping, or unavailable prices.' },
      'agent-6': { role: 'Pricing Delta Analyst', goal: 'Compare normalized catalog evidence with {baseline_file} and separate confirmed changes from uncertain product matches.', backstory: 'A pricing analyst who reports data-quality limitations before recommending action.' },
      'task-5': { label: 'Capture Normalized Catalog Snapshot', description: 'Scrape {competitor_urls}. For each product capture source URL, timestamp, title, SKU if present, variant, currency, current price, reference price, unit basis, availability, and evidence status. Never infer missing prices.', expectedOutput: 'Validated JSON containing snapshot metadata and normalized product records with evidence URLs and nullable missing fields.', outputFormat: 'json' },
      'task-6': { label: 'Compare Baseline and Triage Changes', description: 'Compare the catalog snapshot against {baseline_file}. Match conservatively, calculate deltas only when currency and unit basis agree, flag uncertain matches, and rank confirmed changes by business impact.', expectedOutput: 'A Markdown delta report with confirmed price changes, new/removed products, uncertain matches, calculation assumptions, and recommended manual checks.' },
      'tool-6': { description: 'Search the supplied baseline file containing prior normalized catalog records.' },
    },
  },
  'csv-data-validator': {
    crewName: 'Consent-Aware Contact Data Quality Crew',
    nodeData: {
      'agent-data-inspector': { role: 'Contact Data Quality Analyst', goal: 'Validate {csv_path} against the required columns, normalize safe fields, and quarantine records that cannot be verified.', backstory: 'A privacy-aware data steward who never invents missing contact details and preserves a clear audit trail.' },
      'agent-outreach': { role: 'Consent-Aware Outreach Drafting Specialist', goal: 'Create optional outreach drafts only for records that contain the required identity, lawful-contact, and personalization fields.', backstory: 'A B2B communications editor who avoids sensitive inference, deceptive personalization, and unsupported claims.' },
      'task-verify': { label: 'Validate and Quarantine Contact Records', description: 'Read {csv_path}. Check required columns, encoding, duplicates, email syntax, missing consent/status fields, and unsafe formula-prefixed cells. Do not claim mailbox deliverability. Separate valid, review-required, and rejected rows with reason codes.', expectedOutput: 'Validated JSON with row counts, schema findings, reason-coded rejected rows, and a clean subset containing only supplied values.', outputFormat: 'json' },
      'task-generate-list': { label: 'Prepare Reviewable Outreach Drafts', description: 'Using only valid rows, create concise {outreach_language} drafts based on supplied non-sensitive fields. Include an opt-out line and mark any record lacking personalization evidence for manual review. Do not send messages.', expectedOutput: 'A Markdown review table with contact identifier, supplied personalization evidence, draft subject/body, opt-out text, and approval status.' },
      'tool-csv': { description: 'Read the configured local CSV for validation; this does not verify whether an email inbox exists.' },
    },
  },
  'github-repo-analyzer': {
    crewName: 'Repository Onboarding Documentation Crew',
    nodeData: {
      'agent-code-reviewer': { role: 'Repository Architecture Analyst', goal: 'Map {repository_url} from evidence in code and configuration while distinguishing observations from recommendations.', backstory: 'A principal engineer who cites file paths and avoids claiming runtime behavior that static inspection cannot prove.' },
      'agent-tech-writer': { role: 'Developer Onboarding Writer', goal: 'Turn verified repository findings into accurate onboarding documentation for {target_reader}.', backstory: 'A technical writer who never fabricates installation steps, environment variables, or commands.' },
      'task-analyze-repo': { label: 'Build Evidence-Based Repository Map', description: 'Inspect {repository_url}. Identify entrypoints, major modules, package scripts, dependencies, data stores, external services, tests, and deployment files. Cite file paths for every major claim and list unanswered questions.', expectedOutput: 'A Markdown repository map with evidence paths, verified commands, architecture boundaries, risks, and unanswered questions.' },
      'task-draft-docs': { label: 'Draft Onboarding Documentation', description: 'Using the repository map, draft a README improvement and architecture overview for {target_reader}. Include only verified setup commands and environment-variable names; mark unknown values as TODO rather than inventing them.', expectedOutput: 'Two Markdown documents: a README proposal and architecture overview, each with evidence references and a TODO/verification section.' },
      'tool-github': { description: 'Search code and repository metadata for the configured repository URL using authorized GitHub access.' },
    },
  },
  'youtube-to-blog': {
    crewName: 'Transcript-Grounded Content Repurposing Crew',
    nodeData: {
      'agent-video-extractor': { role: 'Transcript Evidence Editor', goal: 'Extract accurate themes and timestamped evidence from {youtube_url} without inventing quotations.', backstory: 'A media researcher who separates transcript evidence, paraphrase, and interpretation.' },
      'agent-seo-writer': { role: 'Attribution-Safe SEO Editor', goal: 'Adapt the verified transcript brief into a useful article for {target_reader} while preserving attribution.', backstory: 'An SEO editor who values original structure and reader utility over transcript copying or keyword stuffing.' },
      'task-summarize-video': { label: 'Create Timestamped Transcript Brief', description: 'Analyze {youtube_url}. Record the thesis, main arguments, speaker-attributed claims, exact short quotes only when present, timestamps, and unclear transcript passages. Do not guess missing words.', expectedOutput: 'A Markdown transcript brief with timestamps, attributed evidence, paraphrases, notable short quotes, and uncertainty notes.' },
      'task-write-blog': { label: 'Write an Original Attributed Article', description: 'Write a {target_length}-word Markdown article for {target_reader} using the transcript brief. Add an original framing, headings, takeaways, video attribution/link, meta title, and meta description. Do not present speaker opinions as verified facts.', expectedOutput: 'A review-ready original Markdown article with video attribution, timestamp references, SEO metadata, and a factual review checklist.' },
      'tool-youtube': { description: 'Retrieve transcript and metadata for the configured YouTube video; transcript quality may require manual review.' },
    },
  },
  'parallel-web-research': {
    template: { title: '🌐 Parallel Evidence Research & Synthesis', titleEn: '🌐 Parallel Evidence Research & Synthesis', titleJa: '🌐 並列エビデンス調査＆統合' },
    crewName: 'Parallel Evidence Research Crew',
    nodeData: {
      'agent-researcher': { role: 'Multi-Lane Evidence Researcher', goal: 'Investigate {research_question} across evidence, stakeholder, and risk lanes using dated primary sources where possible.', backstory: 'A rigorous web researcher who records provenance, publication dates, and uncertainty for every lane.' },
      'agent-writer': { role: 'Research Synthesis Editor', goal: 'Reconcile independent research lanes into a decision-ready answer to {research_question}.', backstory: 'An analytical editor who highlights conflicts and evidence gaps instead of forcing false consensus.' },
      'task-research-1': { label: 'Evidence and Facts Lane (Async)', description: 'Research {research_question} focusing on primary evidence, definitions, measurable facts, and recent developments. Record dated source links and confidence.', expectedOutput: 'A source table and evidence brief with dates, primary/secondary classification, and confidence notes.', asyncExecution: true },
      'task-research-2': { label: 'Stakeholders and Alternatives Lane (Async)', description: 'Research {research_question} focusing on stakeholder positions, competing approaches, adoption constraints, and credible counterarguments. Record dated sources.', expectedOutput: 'A stakeholder and alternatives brief with cited claims, tradeoffs, and unresolved disagreements.', asyncExecution: true },
      'task-research-3': { label: 'Risk and Validation Lane (Async)', description: 'Research {research_question} focusing on risks, failure cases, missing evidence, regulatory or operational constraints, and ways to validate claims.', expectedOutput: 'A risk register with evidence links, likelihood/impact rationale, and proposed validation steps.', asyncExecution: true },
      'task-synthesis': { label: 'Synthesize Decision-Ready Report', description: 'Answer {research_question} by reconciling all three lanes. Deduplicate claims, expose conflicts, grade evidence strength, and separate findings from recommendations.', expectedOutput: 'A Markdown report with executive answer, evidence table, stakeholder tradeoffs, risk register, disagreements, gaps, and next actions.' },
      'tool-search': { description: 'Search current web sources for the configured research question; every important claim must retain its source URL.' },
    },
  },
  'hierarchical-software-team': {
    template: { title: '💻 Manager-Led Feature Design & Review', titleEn: '💻 Manager-Led Feature Design & Review', titleJa: '💻 階層型機能設計＆レビュー' },
    crewName: 'Manager-Led Feature Design Crew',
    nodeData: {
      'agent-dev': { role: 'Senior Implementation Designer', goal: 'Produce an implementation proposal for {feature_brief} within {technical_constraints}.', backstory: 'A pragmatic full-stack engineer who makes assumptions explicit and produces testable, accessible designs.' },
      'agent-qa': { role: 'Quality and Security Reviewer', goal: 'Challenge the proposed implementation against acceptance criteria, edge cases, accessibility, and security.', backstory: 'A skeptical reviewer who distinguishes review findings from executed test results.' },
      'task-dev': { label: 'Design Feature Implementation', description: 'Given {feature_brief} and {technical_constraints}, propose component boundaries, data flow, typed interfaces, error states, accessibility behavior, and representative code. State assumptions and do not claim files were modified.', expectedOutput: 'A Markdown implementation plan with TypeScript code proposal, interfaces, state/error handling, accessibility notes, and acceptance-criteria mapping.' },
      'task-qa': { label: 'Review Design and Produce Test Plan', description: 'Review the implementation proposal. Identify correctness, security, privacy, accessibility, and maintainability risks. Provide unit/integration test code where possible, but distinguish proposed tests from executed results.', expectedOutput: 'A review report with severity-ranked findings, revised code snippets, test plan/test cases, and explicit unverified items.' },
    },
  },
  'hierarchical-marketing-campaign': {
    template: { title: '📣 Manager-Led Campaign Strategy & Copy Review', titleEn: '📣 Manager-Led Campaign Strategy & Copy Review', titleJa: '📣 階層型キャンペーン設計＆コピーレビュー' },
    crewName: 'Manager-Led Campaign Planning Crew',
    nodeData: {
      'agent-analyst': { role: 'Evidence-Based Market Strategist', goal: 'Research the market, audience, alternatives, and claim constraints for {campaign_brief}.', backstory: 'A market analyst who cites sources and avoids inventing audience statistics.' },
      'agent-copywriter': { role: 'Responsible Performance Copywriter', goal: 'Create channel-appropriate copy grounded in the approved evidence and {brand_constraints}.', backstory: 'A conversion copywriter who avoids deceptive urgency, unsupported superiority claims, and sensitive targeting.' },
      'task-analyze': { label: 'Build Campaign Evidence Brief', description: 'Analyze {campaign_brief}. Research audience needs, alternatives, category language, objections, and claim/compliance risks. Cite sources, flag assumptions, and do not fabricate market size or persona data.', expectedOutput: 'A cited campaign brief with audience hypotheses, evidence, alternatives, messaging angles, prohibited claims, and validation questions.' },
      'task-copy': { label: 'Draft and Self-Review Campaign Variants', description: 'Using the approved brief and {brand_constraints}, create 3 distinct ad variants for {target_channel}. For each, explain the angle, evidence basis, CTA, and claim risk. Include a human approval checklist.', expectedOutput: 'Three review-ready ad variants with rationale, evidence mapping, CTA, risk notes, and approval checklist.' },
      'tool-market': { description: 'Search current market and competitor sources for the configured campaign; retain URLs for substantiation.' },
    },
  },
  'repository-red-team-audit': {
    crewName: 'Read-Only Repository Release Audit Crew',
    nodeData: {
      'rt-agent-architecture': { goal: 'Reconstruct and evaluate the architecture of {repository_path} using read-only evidence.' },
      'rt-agent-security': { goal: 'Identify plausible security weaknesses in {repository_path} without exploitation or modification.' },
      'rt-agent-reliability': { goal: 'Find operational failure modes and recovery gaps in {repository_path} from static evidence.' },
      'rt-agent-adversarial': { goal: 'Design safe, non-destructive validation scenarios; never execute attacks or alter systems.' },
      'rt-agent-cost': { goal: 'Estimate cost drivers from repository evidence and clearly stated usage assumptions.' },
      'rt-task-reconstruct': { description: 'Inspect {repository_path} using read-only tools. Map entrypoints, modules, data flows, external services, trust boundaries, deployment assumptions, and evidence file paths. Record unknowns instead of guessing.' },
      'rt-task-security': { description: 'Perform a non-destructive static security review of {repository_path}. Cover authentication, authorization, input handling, secrets patterns, dependencies, data exposure, and abuse cases. Do not expose secret values or claim exploitability without evidence.' },
      'rt-task-reliability': { description: 'Review static evidence for failure handling, retries, timeouts, idempotency, concurrency, observability, deployment safety, and recovery. Distinguish confirmed implementation from missing or unverified behavior.' },
      'rt-task-cost': { description: 'Analyze likely compute, storage, network, model, and managed-service cost drivers from repository evidence plus {usage_assumptions}. State formulas, assumptions, and uncertainty; do not invent billing data.' },
      'rt-task-release': { description: 'Combine all audit and simulation outputs. Deduplicate findings, grade evidence strength, assign proposed owners and release gates, and produce a go, conditional-go, or no-go recommendation. Treat {output_directory} as the requested destination but do not claim a file was written unless a write-capable tool is configured.' },
    },
    additionalNodes: [
      { id: 'rt-tool-directory', type: 'tool', position: { x: 20, y: 120 }, data: { label: 'Repository Directory Reader', toolType: 'DirectoryReadTool', description: 'List repository files and directories in the configured local path without writing changes.' } },
      { id: 'rt-tool-file', type: 'tool', position: { x: 20, y: 300 }, data: { label: 'Repository File Reader', toolType: 'FileReadTool', description: 'Read selected repository files for evidence without modifying them.' } },
    ],
    additionalEdges: [
      { id: 'rt-e-dir-architecture', source: 'rt-tool-directory', target: 'rt-agent-architecture' },
      { id: 'rt-e-file-architecture', source: 'rt-tool-file', target: 'rt-agent-architecture' },
      { id: 'rt-e-file-security', source: 'rt-tool-file', target: 'rt-agent-security' },
      { id: 'rt-e-file-reliability', source: 'rt-tool-file', target: 'rt-agent-reliability' },
      { id: 'rt-e-file-cost', source: 'rt-tool-file', target: 'rt-agent-cost' },
    ],
  },
};

export const PRESET_TEMPLATES: WorkflowTemplate[] = BASE_PRESET_TEMPLATES.map((template) => ({
  ...template,
  ...TEMPLATE_GUIDES[template.id],
  ...(TEMPLATE_GRAPH_REFINEMENTS[template.id]?.template || {}),
  previewNodesCount: (() => {
    const nodes = [...template.graphData.nodes, ...(TEMPLATE_GRAPH_REFINEMENTS[template.id]?.additionalNodes || [])];
    return {
      agents: nodes.filter((node) => node.type === 'agent').length,
      tasks: nodes.filter((node) => node.type === 'task').length,
      tools: nodes.filter((node) => node.type === 'tool').length,
    };
  })(),
  graphData: {
    crewConfig: {
      ...template.graphData.crewConfig,
      name: TEMPLATE_GRAPH_REFINEMENTS[template.id]?.crewName || template.graphData.crewConfig.name,
    },
    nodes: [...template.graphData.nodes, ...(TEMPLATE_GRAPH_REFINEMENTS[template.id]?.additionalNodes || [])].map((node) => ({
      ...node,
      data: {
        ...node.data,
        ...(TEMPLATE_GRAPH_REFINEMENTS[template.id]?.nodeData[node.id] || {}),
      },
    })) as CustomNode[],
    edges: [...template.graphData.edges, ...(TEMPLATE_GRAPH_REFINEMENTS[template.id]?.additionalEdges || [])],
  },
}));
