import { WorkflowTemplate } from '@/types/editor';

export const PRESET_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'x-trend-auto-poster',
    title: '📱 X (Twitter) Trend Analyst & Auto-Poster',
    titleEn: '📱 X (Twitter) Trend Analyst & Auto-Poster',
    titleJa: '📱 X (Twitter) トレンド分析＆自動投稿ボット',
    description: 'Monitors daily trends, analyzes target audience sentiment, and automatically generates and schedules engaging social media posts.',
    descriptionEn: 'Monitors daily trends, analyzes target audience sentiment, and automatically generates and schedules engaging social media posts.',
    descriptionJa: '毎日のトレンドを監視・分析し、ターゲット層に刺さるSNS投稿を自動生成してスケジュール投稿を準備するエージェント。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'X Trend Auto-Poster Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-1',
          type: 'tool',
          position: { x: 50, y: 80 },
          data: {
            label: 'Google & Social Search',
            toolType: 'SerperDevTool',
            description: 'Search live Google & social trends for target keywords.',
          },
        },
        {
          id: 'tool-2',
          type: 'tool',
          position: { x: 50, y: 220 },
          data: {
            label: 'Brand Tone & Knowledge DB',
            toolType: 'TXTSearchTool',
            description: 'Reference brand guidelines and past viral post performance.',
          },
        },
        {
          id: 'agent-1',
          type: 'agent',
          position: { x: 340, y: 120 },
          data: {
            label: 'Trend Researcher',
            role: 'Viral Social Media Analyst',
            goal: 'Identify real-time trending tech/business topics and extract key sentiment patterns.',
            backstory: 'A data-driven growth marketer specializing in identifying viral social media hooks, emerging industry trends, and high-engagement topics on X/Twitter.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-2',
          type: 'agent',
          position: { x: 340, y: 380 },
          data: {
            label: 'Content Creator',
            role: 'Senior X Copywriter & Content Strategist',
            goal: 'Draft 3 highly engaging, 280-character posts tailored for maximum retweets and impressions.',
            backstory: 'An expert copywriter with a track record of crafting viral tech posts, engaging hooks, concise insights, and clear calls-to-action.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-1',
          type: 'task',
          position: { x: 680, y: 120 },
          data: {
            label: 'Research Live Trends',
            description: 'Search recent tech, AI, and business news from the last 24 hours. Analyze audience interest and identify top 3 viral discussion points.',
            expectedOutput: 'A structured summary of top 3 viral trends with engagement angles and target keywords.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-2',
          type: 'task',
          position: { x: 680, y: 380 },
          data: {
            label: 'Draft & Schedule Posts',
            description: 'Using trend insights and brand guidelines, craft 3 ready-to-post tweets with compelling hooks, strong value propositions, and relevant hashtags.',
            expectedOutput: '3 publication-ready tweet drafts formatted with line breaks, hashtags, and call-to-action.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e1', source: 'tool-1', target: 'agent-1' },
        { id: 'e2', source: 'tool-2', target: 'agent-2' },
        { id: 'e3', source: 'agent-1', target: 'task-1' },
        { id: 'e4', source: 'agent-2', target: 'task-2' },
        { id: 'e5', source: 'task-1', target: 'task-2' },
      ],
    },
  },
  {
    id: 'daily-news-blog-generator',
    title: '📰 Daily News Aggregator & Blog Generator',
    titleEn: '📰 Daily News Aggregator & Blog Generator',
    titleJa: '📰 業界ニュース自動収集＆翻訳ブログライター',
    description: 'Automatically scrapes daily industry news from global sources, translates them, and formats them into ready-to-publish SEO blog posts.',
    descriptionEn: 'Automatically scrapes daily industry news from global sources, translates them, and formats them into ready-to-publish SEO blog posts.',
    descriptionJa: '海外の最新ニュースサイトを毎日自動でスクレイピングし、日本語へ翻訳・要約してSEOに強いブログ記事として出力します。',
    price: 0,
    category: '1. Basic (順次処理)',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'Daily News Aggregator Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-3',
          type: 'tool',
          position: { x: 50, y: 100 },
          data: {
            label: 'Web News Scraper',
            toolType: 'ScrapeWebsiteTool',
            description: 'Extract raw text & headlines from foreign tech blogs.',
          },
        },
        {
          id: 'tool-4',
          type: 'tool',
          position: { x: 50, y: 240 },
          data: {
            label: 'Content Archive Inspector',
            toolType: 'DirectoryReadTool',
            description: 'Inspect local content archives to avoid redundant topics.',
          },
        },
        {
          id: 'agent-3',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'News Scraper',
            role: 'Global Tech News Researcher',
            goal: 'Scrape top tech blogs and extract breaking headlines, key statistics, and main quotes.',
            backstory: 'An automated news gathering specialist monitoring major international tech media 24/7 for breaking AI and software updates.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-4',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'SEO Writer',
            role: 'Bilingual Technical Editor & SEO Specialist',
            goal: 'Synthesize scraped foreign news into comprehensive, publication-ready Japanese SEO blog posts.',
            backstory: 'A seasoned tech journalist who crafts high-ranking Markdown articles with proper H2/H3 headings, meta descriptions, and clear summaries.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-3',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Crawl Breaking News',
            description: 'Scrape target tech news URLs, extract key headlines, publication dates, core announcements, and quote references.',
            expectedOutput: 'A compiled news dossier containing main facts, numbers, and source links.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-4',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Generate SEO Blog Article',
            description: 'Translate and synthesize facts into a 1,000-word Japanese SEO blog post with catchy titles, H2/H3 subheadings, TL;DR bullet points, and key takeaways.',
            expectedOutput: 'A publication-ready Japanese Markdown blog article complete with Meta Description and tags.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e6', source: 'tool-3', target: 'agent-3' },
        { id: 'e7', source: 'tool-4', target: 'agent-4' },
        { id: 'e8', source: 'agent-3', target: 'task-3' },
        { id: 'e9', source: 'agent-4', target: 'task-4' },
        { id: 'e10', source: 'task-3', target: 'task-4' },
      ],
    },
  },
  {
    id: 'competitor-price-monitor',
    title: '🔍 Competitor Price & Product Monitor',
    titleEn: '🔍 Competitor Price & Product Monitor',
    titleJa: '🔍 競合サイト価格＆新着商品モニター',
    description: 'Periodically checks competitor websites for pricing changes or new product launches and generates alert reports.',
    descriptionEn: 'Periodically checks competitor websites for pricing changes or new product launches and generates alert reports.',
    descriptionJa: '定期的に競合他社のウェブサイトを巡回し、価格の変動や新着商品の追加を検知してレポートを作成する監視ボット。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'FREE',
    previewNodesCount: { agents: 2, tasks: 2, tools: 2 },
    graphData: {
      crewConfig: {
        name: 'Competitor Price Monitor Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-5',
          type: 'tool',
          position: { x: 50, y: 100 },
          data: {
            label: 'Competitor E-Commerce Scraper',
            toolType: 'ScrapeWebsiteTool',
            description: 'Fetch competitor product catalogs & pricing tables.',
          },
        },
        {
          id: 'tool-6',
          type: 'tool',
          position: { x: 50, y: 240 },
          data: {
            label: 'Historical Price Database',
            toolType: 'TXTSearchTool',
            description: 'Query past pricing baseline and historical product logs.',
          },
        },
        {
          id: 'agent-5',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Web Monitor',
            role: 'Competitive Intelligence Crawler',
            goal: 'Periodically scan competitor product pages to extract prices, stock status, and product titles.',
            backstory: 'A high-precision web data extractor built to monitor e-commerce catalogs and capture pricing updates reliably.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-6',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Data Analyst',
            role: 'Pricing & Market Intelligence Analyst',
            goal: 'Detect price fluctuations against baseline metrics and produce actionable executive alert summaries.',
            backstory: 'A retail pricing strategist who analyzes competitor price moves, detects discount patterns, and flags strategic market shifts.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-5',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Scrape Competitor Catalog',
            description: 'Scrape target competitor e-commerce listings, extracting SKU names, current prices, original list prices, and stock availability.',
            expectedOutput: 'A structured data matrix of scraped products with titles, prices, and stock statuses.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-6',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Analyze Price Deltas & Alert',
            description: 'Compare scraped prices against historical baseline data. Highlight price cuts, price hikes, or new product additions, and generate alert flags (HIGH/MEDIUM/LOW).',
            expectedOutput: 'An Executive Competitor Alert Memo detailing price changes, percentage shifts, and recommended strategic counter-actions.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e11', source: 'tool-5', target: 'agent-5' },
        { id: 'e12', source: 'tool-6', target: 'agent-6' },
        { id: 'e13', source: 'agent-5', target: 'task-5' },
        { id: 'e14', source: 'agent-6', target: 'task-6' },
        { id: 'e15', source: 'task-5', target: 'task-6' },
      ],
    },
  },
  {
    id: 'csv-data-validator',
    title: '📊 CSV Data Validator & Outreach Crew',
    titleEn: '📊 CSV Data Validator & Outreach Crew',
    titleJa: '📊 データ検証＆英語コンタクトリスト作成',
    description: 'Inspects CSV data for inconsistencies and automatically generates a validated English contact list for outreach.',
    descriptionEn: 'Inspects CSV data for inconsistencies and automatically generates a validated English contact list for outreach.',
    descriptionJa: 'インポートしたCSV等のファイルから宛先件数やデータの不整合を検査し、検証用に抽出した英語のコンタクトリストを自動生成します。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Data Validation & Outreach',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-csv',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'CSV File Analyzer',
            toolType: 'CSVSearchTool',
            description: 'Search and read contents of local CSV files for data extraction.',
          },
        },
        {
          id: 'agent-data-inspector',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Data Quality Inspector',
            role: 'Senior Data Quality Analyst',
            goal: 'Identify data inconsistencies, missing fields, and extract valid rows from the dataset.',
            backstory: 'A meticulous data quality inspector expert at finding anomalies, cleaning up messy datasets, and ensuring data integrity for enterprise systems.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-outreach',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Outreach Specialist',
            role: 'Multilingual Outreach Specialist',
            goal: 'Generate a professional English contact list and personalized outreach message templates.',
            backstory: 'An expert outreach specialist and copywriter who crafts highly engaging, professional, and personalized contact emails in English.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-verify',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Verify Destination Counts',
            description: 'Search through the provided CSV file to verify the total count of valid destination records. Find any missing or malformed data fields (e.g. invalid emails).',
            expectedOutput: 'A detailed validation report containing valid record counts, error logs, and a cleaned data subset.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-generate-list',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Generate English Contact List',
            description: 'Using the cleaned data subset from the validation report, generate a formal English contact list with personalized outreach message templates for each verified contact.',
            expectedOutput: 'A Markdown table containing the contact list along with customized English message templates.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-csv1', source: 'tool-csv', target: 'agent-data-inspector' },
        { id: 'e-csv2', source: 'agent-data-inspector', target: 'task-verify' },
        { id: 'e-csv3', source: 'agent-outreach', target: 'task-generate-list' },
        { id: 'e-csv4', source: 'task-verify', target: 'task-generate-list' },
      ],
    },
  },
  {
    id: 'github-repo-analyzer',
    title: '💻 GitHub Repo Analyzer & Doc Gen',
    titleEn: '💻 GitHub Repo Analyzer & Doc Gen',
    titleJa: '💻 GitHubコードレビュー＆ドキュメント生成',
    description: 'Analyzes GitHub repositories for code quality and automatically drafts comprehensive technical documentation.',
    descriptionEn: 'Analyzes GitHub repositories for code quality and automatically drafts comprehensive technical documentation.',
    descriptionJa: '指定したGitHubリポジトリを読み込んでコード品質をレビューし、分かりやすいREADMEや技術解説ドキュメントを生成します。',
    price: 0,
    category: '3. Use Cases (実務フロー)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'GitHub Repo Analyzer',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'tool-github',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'GitHub Code Search',
            toolType: 'GithubSearchTool',
            description: 'Search and read source code from GitHub repositories.',
          },
        },
        {
          id: 'agent-code-reviewer',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Senior Code Reviewer',
            role: 'Principal Software Engineer',
            goal: 'Review the GitHub repository code structure and identify potential improvements, bugs, or architectural flaws.',
            backstory: 'A veteran software engineer with 15+ years of experience in system architecture, design patterns, and enforcing code quality standards across large codebases.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-tech-writer',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Technical Writer',
            role: 'Senior Technical Writer',
            goal: 'Draft comprehensive and developer-friendly technical documentation based on the code analysis.',
            backstory: 'A skilled technical writer capable of translating complex code architectures and logic into clear, engaging, and easy-to-read developer documentation.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-analyze-repo',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Analyze Repo Structure',
            description: 'Search through the target GitHub repository. Analyze the file structure, core dependencies, and review the main application logic for code quality and potential anti-patterns.',
            expectedOutput: 'A comprehensive technical code review report highlighting strengths, weaknesses, and architectural suggestions.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-draft-docs',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Draft Documentation',
            description: 'Take the technical code review report and draft a clear, well-structured README.md file and technical architecture document. Make sure to explain the core functionalities simply.',
            expectedOutput: 'A polished README.md file and an accompanying technical overview document in Markdown format.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-gh1', source: 'tool-github', target: 'agent-code-reviewer' },
        { id: 'e-gh2', source: 'agent-code-reviewer', target: 'task-analyze-repo' },
        { id: 'e-gh3', source: 'agent-tech-writer', target: 'task-draft-docs' },
        { id: 'e-gh4', source: 'task-analyze-repo', target: 'task-draft-docs' },
      ],
    },
  },
  {
    id: 'youtube-to-blog',
    title: '▶️ YouTube to Blog Post Converter',
    titleEn: '▶️ YouTube to Blog Post Converter',
    titleJa: '▶️ YouTube動画からSEOブログ自動生成',
    description: 'Extracts content from YouTube videos and restructures it into fully formatted, SEO-optimized blog articles.',
    descriptionEn: 'Extracts content from YouTube videos and restructures it into fully formatted, SEO-optimized blog articles.',
    descriptionJa: 'YouTube動画のURLから内容を抽出し、要約だけでなくSEOに最適化された見出し付きのブログ記事に再構築します。',
    price: 0,
    category: '1. Basic (順次処理)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'YouTube Content Repurposer',
        process: 'sequential',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-youtube',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'YouTube Transcript Extractor',
            toolType: 'YoutubeVideoSearchTool',
            description: 'Extract transcripts and metadata from YouTube videos.',
          },
        },
        {
          id: 'agent-video-extractor',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Video Content Extractor',
            role: 'Expert Media Analyst',
            goal: 'Extract the main ideas, quotes, and narrative structure from a given YouTube video transcript.',
            backstory: 'An expert media analyst capable of breaking down long-form video content into core concepts, key takeaways, and actionable insights.',
            model: 'gpt-5.6-luna',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-seo-writer',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'SEO Content Writer',
            role: 'Senior SEO Blog Writer',
            goal: 'Transform video summaries into comprehensive, SEO-optimized blog posts that rank high on Google.',
            backstory: 'A seasoned SEO blog writer who specializes in creating engaging, high-ranking content optimized for search engines, with perfect formatting and readability.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-summarize-video',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Summarize Video Concepts',
            description: 'Analyze the transcript of the provided YouTube video URL. Extract the primary thesis, 3-5 main supporting arguments, and any notable quotes.',
            expectedOutput: 'A structured summary of the video content, organized logically by main themes and key takeaways.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-write-blog',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Write Blog Article',
            description: 'Using the extracted video concepts, write a compelling, 1500-word SEO-optimized blog post. Include a catchy H1 title, well-structured H2/H3 headings, and an introductory hook.',
            expectedOutput: 'A fully formatted Markdown blog post ready for publishing, complete with SEO meta title and description.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-yt1', source: 'tool-youtube', target: 'agent-video-extractor' },
        { id: 'e-yt2', source: 'agent-video-extractor', target: 'task-summarize-video' },
        { id: 'e-yt3', source: 'agent-seo-writer', target: 'task-write-blog' },
        { id: 'e-yt4', source: 'task-summarize-video', target: 'task-write-blog' },
      ],
    },
  },
  {
    id: 'parallel-web-research',
    title: '🌐 Parallel Web Research',
    titleEn: '🌐 Parallel Web Research',
    titleJa: '🌐 Web並行リサーチ＆レポート (非同期)',
    description: 'Searches multiple sources concurrently and synthesizes findings into a single report.',
    descriptionEn: 'Searches multiple sources concurrently and synthesizes findings into a single report.',
    descriptionJa: '複数のタスクを非同期（並行）で実行し、Webリサーチを高速化。最後に結果を統合します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 4, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Parallel Research Crew',
        process: 'sequential',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-search',
          type: 'tool',
          position: { x: 50, y: 220 },
          data: {
            label: 'Web Search Tool',
            toolType: 'SerperDevTool',
            description: 'Search the web for real-time information.',
          },
        },
        {
          id: 'agent-researcher',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Web Researcher',
            role: 'Expert Web Researcher',
            goal: 'Find accurate and up-to-date information on the web.',
            backstory: 'An expert researcher capable of finding anything on the web.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-writer',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Report Writer',
            role: 'Senior Technical Writer',
            goal: 'Synthesize research findings into a comprehensive report.',
            backstory: 'A technical writer who excels at combining multiple sources into cohesive reports.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-research-1',
          type: 'task',
          position: { x: 680, y: 50 },
          data: {
            label: 'Research Topic A (Async)',
            description: 'Search for the latest news on Artificial Intelligence.',
            expectedOutput: 'Summary of recent AI news.',
            asyncExecution: true,
          },
        },
        {
          id: 'task-research-2',
          type: 'task',
          position: { x: 680, y: 180 },
          data: {
            label: 'Research Topic B (Async)',
            description: 'Search for the latest news on Quantum Computing.',
            expectedOutput: 'Summary of recent Quantum Computing news.',
            asyncExecution: true,
          },
        },
        {
          id: 'task-research-3',
          type: 'task',
          position: { x: 680, y: 310 },
          data: {
            label: 'Research Topic C (Async)',
            description: 'Search for the latest news on Space Exploration.',
            expectedOutput: 'Summary of recent Space Exploration news.',
            asyncExecution: true,
          },
        },
        {
          id: 'task-synthesis',
          type: 'task',
          position: { x: 960, y: 400 },
          data: {
            label: 'Synthesize Report',
            description: 'Combine the findings from all three research tasks into a single comprehensive report.',
            expectedOutput: 'A unified Markdown report.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-r1', source: 'tool-search', target: 'agent-researcher' },
        { id: 'e-r2', source: 'agent-researcher', target: 'task-research-1' },
        { id: 'e-r3', source: 'agent-researcher', target: 'task-research-2' },
        { id: 'e-r4', source: 'agent-researcher', target: 'task-research-3' },
        { id: 'e-r5', source: 'agent-writer', target: 'task-synthesis' },
        { id: 'e-r6', source: 'task-research-1', target: 'task-synthesis' },
        { id: 'e-r7', source: 'task-research-2', target: 'task-synthesis' },
        { id: 'e-r8', source: 'task-research-3', target: 'task-synthesis' },
      ],
    },
  },
  {
    id: 'hierarchical-software-team',
    title: '💻 Hierarchical Software Team',
    titleEn: '💻 Hierarchical Software Team',
    titleJa: '💻 階層型ソフトウェア開発チーム (Manager AI)',
    description: 'A Manager AI oversees a Senior Developer and a QA Engineer to build robust software.',
    descriptionEn: 'A Manager AI oversees a Senior Developer and a QA Engineer to build robust software.',
    descriptionJa: 'マネージャーAIがタスクを分割し、開発者とQAエンジニアに委任してソフトウェアを開発します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 0 },
    graphData: {
      crewConfig: {
        name: 'Hierarchical Software Team',
        process: 'hierarchical',
        managerLlm: 'gpt-5.6-terra',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'agent-dev',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Senior Developer',
            role: 'Senior Full Stack Developer',
            goal: 'Write clean, scalable, and efficient code based on requirements.',
            backstory: 'A senior developer with 10 years of experience in React and Node.js.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-qa',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'QA Engineer',
            role: 'Quality Assurance Engineer',
            goal: 'Test code thoroughly and find any edge cases or bugs.',
            backstory: 'A meticulous QA engineer who ensures zero defects in production.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-dev',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Develop Feature',
            description: 'Develop a fully functional login form component with validation in React and TypeScript.',
            expectedOutput: 'Complete, clean source code for the login form component.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-qa',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'QA and Security Review',
            description: 'Inspect the developed login form component, write unit tests, and verify edge cases and input validation.',
            expectedOutput: 'QA test report with test suite code and verification status.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-h1', source: 'agent-dev', target: 'task-dev' },
        { id: 'e-h2', source: 'agent-qa', target: 'task-qa' },
        { id: 'e-h3', source: 'task-dev', target: 'task-qa' }
      ],
    },
  },
  {
    id: 'hierarchical-marketing-campaign',
    title: '📣 Hierarchical Marketing Campaign',
    titleEn: '📣 Hierarchical Marketing Campaign',
    titleJa: '📣 階層型マーケティング・キャンペーン (Manager AI)',
    description: 'A Manager AI orchestrates a Market Analyst and a Copywriter to create a cohesive campaign.',
    descriptionEn: 'A Manager AI orchestrates a Market Analyst and a Copywriter to create a cohesive campaign.',
    descriptionJa: 'マネージャーAIが市場アナリストとコピーライターを統括し、一貫性のあるキャンペーンを構築します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 2, tasks: 2, tools: 1 },
    graphData: {
      crewConfig: {
        name: 'Marketing Campaign Crew',
        process: 'hierarchical',
        managerLlm: 'gpt-5.6-terra',
        verbose: true,
        memory: false,
      },
      nodes: [
        {
          id: 'tool-market',
          type: 'tool',
          position: { x: 50, y: 140 },
          data: {
            label: 'Web Search',
            toolType: 'SerperDevTool',
            description: 'Search for market trends and competitors.',
          },
        },
        {
          id: 'agent-analyst',
          type: 'agent',
          position: { x: 340, y: 140 },
          data: {
            label: 'Market Analyst',
            role: 'Senior Market Analyst',
            goal: 'Analyze market trends and identify target audience segments.',
            backstory: 'An expert in reading market trends and finding lucrative niches.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'agent-copywriter',
          type: 'agent',
          position: { x: 340, y: 400 },
          data: {
            label: 'Copywriter',
            role: 'Direct Response Copywriter',
            goal: 'Create high-converting ad copy based on market analysis.',
            backstory: 'A legendary copywriter known for writing ads that generate millions in revenue.',
            model: 'anthropic/claude-3-5-sonnet-latest',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'task-analyze',
          type: 'task',
          position: { x: 680, y: 140 },
          data: {
            label: 'Analyze Target Market',
            description: 'Research the current market for eco-friendly sneakers.',
            expectedOutput: 'A detailed market analysis report.',
            asyncExecution: false,
          },
        },
        {
          id: 'task-copy',
          type: 'task',
          position: { x: 680, y: 400 },
          data: {
            label: 'Write Ad Copy',
            description: 'Write 3 Facebook ad variations targeting the audience identified in the market analysis.',
            expectedOutput: '3 polished Facebook ad copies.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'e-m1', source: 'tool-market', target: 'agent-analyst' },
        { id: 'e-m2', source: 'agent-analyst', target: 'task-analyze' },
        { id: 'e-m3', source: 'agent-copywriter', target: 'task-copy' },
        { id: 'e-m4', source: 'task-analyze', target: 'task-copy' }
      ],
    },
  },
  {
    id: 'repository-red-team-audit',
    title: '🛡️ Repository Red-Team Audit',
    titleEn: '🛡️ Repository Red-Team Audit',
    titleJa: '🛡️ リポジトリ・レッドチーム監査',
    description: 'Runs architecture, security, reliability, adversarial, and cost reviews before producing a release decision.',
    descriptionEn: 'Runs architecture, security, reliability, adversarial, and cost reviews before producing a release decision.',
    descriptionJa: '設計・セキュリティ・信頼性・攻撃シミュレーション・コストを分担して監査し、最終リリース判定を作成します。',
    price: 0,
    category: '2. Advanced (階層型/非同期)',
    badge: 'NEW',
    previewNodesCount: { agents: 6, tasks: 7, tools: 0 },
    graphData: {
      crewConfig: {
        name: 'Repository Red-Team Audit Crew',
        process: 'sequential',
        verbose: true,
        memory: true,
      },
      nodes: [
        {
          id: 'rt-agent-architecture',
          type: 'agent',
          position: { x: 80, y: 80 },
          data: {
            label: 'Architecture Inspector',
            role: 'Software Architecture Inspector',
            goal: 'Reconstruct and evaluate the architecture of {repository_path}.',
            backstory: 'A principal architect who maps unfamiliar systems and identifies risky coupling, unclear boundaries, and maintainability issues.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-security',
          type: 'agent',
          position: { x: 80, y: 260 },
          data: {
            label: 'Security Red Teamer',
            role: 'Application Security Red Teamer',
            goal: 'Identify exploitable security weaknesses without modifying the repository.',
            backstory: 'An application security specialist experienced in threat modeling, dependency risk, secrets exposure, and abuse-case analysis.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-reliability',
          type: 'agent',
          position: { x: 80, y: 440 },
          data: {
            label: 'Reliability Engineer',
            role: 'Site Reliability Engineer',
            goal: 'Find failure modes, operational gaps, and recovery risks.',
            backstory: 'A production reliability engineer focused on graceful degradation, observability, concurrency, and disaster recovery.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-adversarial',
          type: 'agent',
          position: { x: 80, y: 620 },
          data: {
            label: 'Adversarial Tester',
            role: 'Adversarial Test Designer',
            goal: 'Design safe, non-destructive simulations for the combined audit findings.',
            backstory: 'A test strategist who turns architectural, security, and reliability concerns into reproducible negative test scenarios.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-cost',
          type: 'agent',
          position: { x: 80, y: 800 },
          data: {
            label: 'Cost Auditor',
            role: 'Cloud Cost Auditor',
            goal: 'Estimate operational cost drivers and identify avoidable spend.',
            backstory: 'A FinOps specialist who evaluates infrastructure choices, scaling assumptions, and third-party service costs.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-agent-release',
          type: 'agent',
          position: { x: 80, y: 980 },
          data: {
            label: 'Release Judge',
            role: 'Independent Release Judge',
            goal: 'Issue an evidence-based release recommendation from all audit outputs.',
            backstory: 'An independent engineering leader who prioritizes findings, records uncertainty, and defines explicit release gates.',
            model: 'gpt-5.6-terra',
            verbose: true,
            allowDelegation: false,
          },
        },
        {
          id: 'rt-task-reconstruct',
          type: 'task',
          position: { x: 430, y: 80 },
          data: {
            label: 'Graph Reconstruction',
            description: 'Inspect {repository_path} in read-only mode. Map entrypoints, modules, data flows, external services, trust boundaries, and deployment assumptions.',
            expectedOutput: 'A Markdown architecture map with components, boundaries, data flows, assumptions, and evidence references.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-architecture',
          type: 'task',
          position: { x: 760, y: 80 },
          data: {
            label: 'Architecture Audit',
            description: 'Using the reconstructed graph, assess coupling, ownership boundaries, maintainability, scalability, and unsafe architectural assumptions.',
            expectedOutput: 'A prioritized architecture audit with severity, evidence, impact, and remediation for every finding.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-security',
          type: 'task',
          position: { x: 760, y: 270 },
          data: {
            label: 'Security Audit',
            description: 'Perform a non-destructive security review of {repository_path}. Cover authentication, authorization, input handling, secrets, dependencies, data exposure, and abuse cases.',
            expectedOutput: 'A prioritized security audit with threat scenario, evidence, likelihood, impact, and remediation for each finding.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-reliability',
          type: 'task',
          position: { x: 760, y: 460 },
          data: {
            label: 'Reliability Audit',
            description: 'Review failure handling, retries, timeouts, idempotency, concurrency, observability, deployment safety, and recovery procedures.',
            expectedOutput: 'A reliability risk register with failure mode, trigger, user impact, detectability, and mitigation.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-adversarial',
          type: 'task',
          position: { x: 1080, y: 360 },
          data: {
            label: 'Adversarial Simulation',
            description: 'Synthesize the architecture, security, and reliability audits into safe test scenarios. Do not execute destructive actions or alter external systems.',
            expectedOutput: 'A non-destructive adversarial test plan with preconditions, steps, expected signals, stop conditions, and success criteria.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-cost',
          type: 'task',
          position: { x: 760, y: 720 },
          data: {
            label: 'Cost Analysis',
            description: 'Analyze likely compute, storage, network, model, and managed-service costs. State assumptions and identify the largest cost sensitivities.',
            expectedOutput: 'A cost analysis with assumptions, primary drivers, optimization options, and uncertainty ranges.',
            asyncExecution: false,
          },
        },
        {
          id: 'rt-task-release',
          type: 'task',
          position: { x: 1400, y: 500 },
          data: {
            label: 'Release Report',
            description: 'Combine every audit and simulation result. Deduplicate findings, assign owners and release gates, and produce a final go, conditional-go, or no-go recommendation for {output_directory}.',
            expectedOutput: 'A structured JSON release report with decision, blockers, prioritized findings, owners, release gates, and residual risks.',
            asyncExecution: false,
          },
        },
      ],
      edges: [
        { id: 'rt-e-a-reconstruct', source: 'rt-agent-architecture', target: 'rt-task-reconstruct' },
        { id: 'rt-e-a-architecture', source: 'rt-agent-architecture', target: 'rt-task-architecture' },
        { id: 'rt-e-a-security', source: 'rt-agent-security', target: 'rt-task-security' },
        { id: 'rt-e-a-reliability', source: 'rt-agent-reliability', target: 'rt-task-reliability' },
        { id: 'rt-e-a-adversarial', source: 'rt-agent-adversarial', target: 'rt-task-adversarial' },
        { id: 'rt-e-a-cost', source: 'rt-agent-cost', target: 'rt-task-cost' },
        { id: 'rt-e-a-release', source: 'rt-agent-release', target: 'rt-task-release' },
        { id: 'rt-e-reconstruct-architecture', source: 'rt-task-reconstruct', target: 'rt-task-architecture' },
        { id: 'rt-e-reconstruct-security', source: 'rt-task-reconstruct', target: 'rt-task-security' },
        { id: 'rt-e-reconstruct-reliability', source: 'rt-task-reconstruct', target: 'rt-task-reliability' },
        { id: 'rt-e-architecture-adversarial', source: 'rt-task-architecture', target: 'rt-task-adversarial' },
        { id: 'rt-e-security-adversarial', source: 'rt-task-security', target: 'rt-task-adversarial' },
        { id: 'rt-e-reliability-adversarial', source: 'rt-task-reliability', target: 'rt-task-adversarial' },
        { id: 'rt-e-architecture-release', source: 'rt-task-architecture', target: 'rt-task-release' },
        { id: 'rt-e-security-release', source: 'rt-task-security', target: 'rt-task-release' },
        { id: 'rt-e-reliability-release', source: 'rt-task-reliability', target: 'rt-task-release' },
        { id: 'rt-e-adversarial-release', source: 'rt-task-adversarial', target: 'rt-task-release' },
        { id: 'rt-e-cost-release', source: 'rt-task-cost', target: 'rt-task-release' },
      ],
    },
  },
];
