'use client';
import type { Language } from '@/lib/i18n/translations';
import type { ArchitectureReviewClientState,ArchitectureReviewEvidenceBundleV0 } from '@/types/architecture-review';

interface Props{state:ArchitectureReviewClientState;evidence:ArchitectureReviewEvidenceBundleV0|null;eligible:boolean;lang:Language;onRun:()=>void;onLocate:(targetKey:string)=>void;currentTargetKeys:ReadonlySet<string>}
const box='rounded-2xl border border-slate-700 bg-slate-900/70 p-4';
export function ArchitectureReviewStageContent({state,evidence,eligible,lang,onRun,onLocate,currentTargetKeys}:Props){const ja=lang==='ja';const result=state.result;const loading=state.status==='loading';const canRun=eligible&&!loading;const runLabel=result?(ja?'もう一度レビュー':'Review again'):(ja?'アーキテクチャレビューを実行':'Run Architecture Review');const evidenceById=new Map(evidence?.items.map((item)=>[item.evidenceId,item])??[]);const targetByKey=new Map(evidence?.targets.map((target)=>[target.targetKey,target])??[]);
  const locate=(keys:readonly string[])=>keys.find((key)=>key.startsWith('node:')&&currentTargetKeys.has(key));
  return <section aria-busy={loading} className="space-y-4"><div><h3 className="text-base font-bold text-white">{ja?'アーキテクチャレビュー':'Architecture Review'}</h3><p className="mt-2 text-xs leading-relaxed text-slate-300">{ja?'既存の決定的Preflightを根拠として、AIが独立した解釈レイヤーを提供します。決定的分析の代替ではありません。':'An AI, evidence-grounded interpretive layer beside deterministic Preflight. It does not replace deterministic analysis.'}</p><p className="mt-2 rounded-xl border border-amber-800/70 bg-amber-950/20 p-3 text-xs leading-relaxed text-amber-100">{ja?'実行すると、role・goal・taskテキストなど必要な設定済みworkflow evidenceがAI providerへ送信されます。選択時のみ実行され、workflowは変更しません。':'Running AI review sends the necessary configured workflow evidence, such as roles, goals, and task text, to the AI provider. It runs only when you choose it and does not change your workflow.'}</p><p className="mt-2 text-xs text-slate-400">{ja?'根拠ソース: Readiness / Execution / Resources':'Evidence sources: Readiness / Execution / Resources'}</p></div>
    {state.status==='not_ready'?<div className={box}><p className="font-bold text-white">{ja?'Preflight evidenceが必要です':'Needs Preflight evidence'}</p><p className="mt-2 text-xs text-slate-400">{state.reason==='empty'?(ja?'ノードを追加してください。':'Add workflow nodes first.'):state.reason==='invalid'?(ja?'ReadinessのValidation問題を解決してください。':'Resolve the Readiness validation issues first.'):(ja?'3つの決定的レビューが利用可能になるまで待ってください。':'Wait until all three deterministic review sources are available.')}</p></div>:null}
    {state.status==='error'?<div role="alert" className="rounded-xl border border-red-800 bg-red-950/30 p-3"><p className="text-sm font-bold text-red-200">{ja?'AIレビューを利用できませんでした':'Architecture Review unavailable'}</p><p className="mt-1 text-xs text-red-100">{state.errorCode==='rate_limited'?(ja?'AIレビューの利用上限です。決定的Preflightは引き続き利用できます。':'AI review is rate limited. Deterministic Preflight remains available.'):(ja?'Providerの問題によりレビューできませんでした。決定的Preflightには影響しません。':'The provider could not complete the review. Deterministic Preflight is unaffected.')}</p></div>:null}
    {state.stale?<div role="status" aria-live="polite" className="rounded-xl border border-amber-700 bg-amber-950/30 p-3 text-xs text-amber-100"><strong>{ja?'Workflowが変更されました':'Workflow changed'}</strong><p className="mt-1">{ja?'以前の結果を保持しています。更新するには再レビューしてください。':'The previous result is retained. Run the review again to update it.'}</p></div>:null}
    {result?<Result result={result} ja={ja} evidenceById={evidenceById} targetByKey={targetByKey} onLocate={onLocate} locate={locate}/>:null}
    {!result&&state.status==='idle'?<div className={box}><p className="text-sm font-bold text-white">{ja?'未レビュー':'Not reviewed'}</p><p className="mt-2 text-xs text-slate-400">{ja?'明示的に実行するまでAIへの送信はありません。':'Nothing is sent to the AI provider until you explicitly run the review.'}</p></div>:null}
    <button type="button" disabled={!canRun} onClick={onRun} className="min-h-11 rounded-lg bg-indigo-500 px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-300">{loading?(ja?'レビュー中…':'Reviewing…'):runLabel}</button><div aria-live="polite" className="sr-only">{state.status==='available'?(ja?'アーキテクチャレビューが完了しました':'Architecture review completed'):''}</div>
  </section>}

function Result({result,ja,evidenceById,targetByKey,onLocate,locate}:any){const most=result.findings[0];const section=(title:string,body:any)=><section className={box}><h4 className="text-sm font-bold text-white">{title}</h4>{body}</section>;const finding=(item:any)=><article key={item.id} className="mt-3 rounded-xl border border-slate-700 p-3"><p className="text-xs font-bold text-indigo-200">{item.priority} · {item.class} · {item.knowledgeStatus}</p><p className="mt-2 text-sm font-semibold text-white">{item.problem}</p><p className="mt-2 text-xs text-slate-300"><strong>{ja?'理由':'Why'}:</strong> {item.why}</p><p className="mt-2 text-xs text-slate-300"><strong>{ja?'推奨':'Recommendation'}:</strong> {item.recommendation}</p><p className="mt-2 text-xs text-slate-300"><strong>{ja?'期待効果':'Expected effect'}:</strong> {item.expectedEffect}</p>{locate(item.targetRefs)?<button type="button" onClick={()=>onLocate(locate(item.targetRefs))} className="mt-3 min-h-11 rounded-lg border border-teal-700 px-3 text-xs font-bold text-teal-200">Locate</button>:null}</article>;
return <div className="space-y-4">{section(ja?'このworkflowが行うと考えられること':'What this workflow appears to do',<><p className="mt-2 text-sm text-slate-200">{result.intent.summary}</p><p className="mt-2 text-xs text-slate-400">{result.intent.knowledgeStatus}</p></>)}{section(ja?'最も重要な問題':'Most important issue',most?finding(most):<p className="mt-2 text-xs text-slate-300">{ja?'このヒューリスティックレビューでは、優先すべきアーキテクチャ所見は生成されませんでした。制約と根拠を引き続き確認してください。':'This heuristic review produced no prioritized architecture finding. Continue to review its evidence and limitations.'}</p>)}{section(ja?'推奨する方向性':'Recommended direction',<p className="mt-2 text-sm text-slate-200">{result.recommendedDirection}</p>)}{section(ja?'強み':'Strengths',result.strengths.length?result.strengths.map((x:any)=><article key={x.id} className="mt-3"><p className="text-sm font-semibold text-white">{x.statement}</p><p className="mt-1 text-xs text-slate-300">{x.whyItHelps}</p><p className="text-xs text-slate-500">{x.knowledgeStatus}</p></article>):<p className="mt-2 text-xs text-slate-400">—</p>)}{section(ja?'その他のアーキテクチャ所見':'Other architecture findings',result.findings.slice(1).length?result.findings.slice(1).map(finding):<p className="mt-2 text-xs text-slate-400">—</p>)}{section(ja?'不確実性':'Uncertainties',result.uncertainties.length?<ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-slate-300">{result.uncertainties.map((x:any)=><li key={x.id}>{x.statement} · {x.knowledgeStatus}</li>)}</ul>:<p className="mt-2 text-xs text-slate-400">—</p>)}{section(ja?'レビューの制約':'Review limitations',<ul className="mt-2 list-disc pl-4 text-xs text-slate-300">{result.limitations.map((x:string)=><li key={x}>{x.replaceAll('_',' ')}</li>)}</ul>)}{section(ja?'Evidence / Reviewer詳細':'Evidence / Reviewer details',<details className="mt-2"><summary className="min-h-11 cursor-pointer text-xs font-bold text-teal-200">{ja?'根拠の詳細を表示':'Show evidence details'}</summary><div className="space-y-2">{[...new Set([...result.intent.evidenceRefs,...result.strengths.flatMap((x:any)=>x.evidenceRefs),...result.findings.flatMap((x:any)=>x.evidenceRefs),...result.uncertainties.flatMap((x:any)=>x.evidenceRefs)])].map((id:any)=>{const item:any=evidenceById.get(id);return item?<div key={id} className="rounded-lg bg-slate-950 p-2 text-xs"><p>{item.source} · {item.knowledgeStatus}</p><p className="text-slate-300">{item.summary}</p><p className="text-slate-500">{item.targetKeys.map((key:string)=>targetByKey.get(key)?.label??key).join(', ')}</p><p className="text-slate-600">{id} · {item.sourceVersion}{item.deterministicFindingRef?` · ${item.deterministicFindingRef}`:''}</p></div>:null})}<p className="text-xs text-slate-500">{result.reviewer.providerId} · {result.reviewer.modelId} · {result.reviewer.locale} · {result.reviewer.generatedAt}</p></div></details>)}</div>}
