'use client';
import type { Language } from '@/lib/i18n/translations';
import type { ArchitectureReviewClientState,ArchitectureReviewErrorCode,ArchitectureReviewEvidenceBundleV0 } from '@/types/architecture-review';
import type { ReturnTypeOfUseArchitectureReview } from '@/hooks/useArchitectureReview';
import { useState } from 'react';

interface Props{state:ArchitectureReviewClientState;evidence:ArchitectureReviewEvidenceBundleV0|null;eligible:boolean;paid:ReturnTypeOfUseArchitectureReview['paid'];lang:Language;onRun:()=>void;onLocate:(targetKey:string)=>void;currentTargetKeys:ReadonlySet<string>}
const box='rounded-2xl border border-slate-700 bg-slate-900/70 p-4';
export function ArchitectureReviewStageContent({state,evidence,eligible,paid,lang,onRun,onLocate,currentTargetKeys}:Props){const ja=lang==='ja';const result=state.result;const loading=state.status==='loading';const canRun=eligible&&paid.canRun&&!loading;const runLabel=result?(ja?'もう一度レビュー':'Review again'):(ja?'アーキテクチャレビューを実行':'Run Architecture Review');const evidenceById=new Map(evidence?.items.map((item)=>[item.evidenceId,item])??[]);const targetByKey=new Map(evidence?.targets.map((target)=>[target.targetKey,target])??[]);
  const locate=(keys:readonly string[])=>keys.find((key)=>key.startsWith('node:')&&currentTargetKeys.has(key));
  return <section aria-busy={loading} className="space-y-4"><div><h3 className="text-base font-bold text-white">{ja?'AIアーキテクチャレビュー':'AI Architecture Review'}</h3><p className="mt-2 text-xs leading-relaxed text-slate-300">{ja?'既存の決定的Preflightを根拠として、AIが独立した解釈レイヤーを提供します。決定的分析の代替ではありません。':'An AI, evidence-grounded interpretive layer beside deterministic Preflight. It does not replace deterministic analysis.'}</p><p className="mt-2 text-xs font-semibold text-teal-200">{ja?'決定論的なワークフロー設計とPreflightは無料のままです。AI Architecture Reviewは利用上限のある有料機能です。':'Deterministic workflow design and Preflight remain free. AI Architecture Review is a paid, usage-limited feature.'}</p><p className="mt-2 rounded-xl border border-amber-800/70 bg-amber-950/20 p-3 text-xs leading-relaxed text-amber-100">{ja?'実行すると、必要最小限のworkflow由来表現がAI providerへ送信されます。secretとtool parameter値は除外され、workflowは変更されません。':'Running review sends the minimum necessary workflow-derived representation to the configured AI provider. Secrets and tool parameter values are excluded; it does not change your workflow.'}</p><p className="mt-2 text-xs text-slate-400">{ja?'根拠ソース: Readiness / Execution / Resources':'Evidence sources: Readiness / Execution / Resources'}</p></div>
    <PaidAccess paid={paid} ja={ja}/>
    {state.status==='not_ready'?<div className={box}><p className="font-bold text-white">{ja?'Preflight evidenceが必要です':'Needs Preflight evidence'}</p><p className="mt-2 text-xs text-slate-400">{state.reason==='empty'?(ja?'ノードを追加してください。':'Add workflow nodes first.'):state.reason==='invalid'?(ja?'ReadinessのValidation問題を解決してください。':'Resolve the Readiness validation issues first.'):(ja?'3つの決定的レビューが利用可能になるまで待ってください。':'Wait until all three deterministic review sources are available.')}</p></div>:null}
    {state.status==='error'?<div role="alert" className="rounded-xl border border-red-800 bg-red-950/30 p-3"><p className="text-sm font-bold text-red-200">{ja?'AIレビューを利用できませんでした':'Architecture Review unavailable'}</p><p className="mt-1 text-xs text-red-100">{reviewFailureMessage(state.errorCode,ja)}</p></div>:null}
    {state.stale?<div role="status" aria-live="polite" className="rounded-xl border border-amber-700 bg-amber-950/30 p-3 text-xs text-amber-100"><strong>{ja?'Workflowが変更されました':'Workflow changed'}</strong><p className="mt-1">{ja?'以前の結果を保持しています。更新するには再レビューしてください。':'The previous result is retained. Run the review again to update it.'}</p></div>:null}
    {result?<Result result={result} ja={ja} evidenceById={evidenceById} targetByKey={targetByKey} onLocate={onLocate} locate={locate}/>:null}
    {!result&&state.status==='idle'?<div className={box}><p className="text-sm font-bold text-white">{ja?'未レビュー':'Not reviewed'}</p><p className="mt-2 text-xs text-slate-400">{ja?'明示的に実行するまでAIへの送信はありません。':'Nothing is sent to the AI provider until you explicitly run the review.'}</p></div>:null}
    <button type="button" disabled={!canRun} onClick={onRun} className="min-h-11 rounded-lg bg-indigo-500 px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-300">{loading?(ja?'レビュー中…':'Reviewing…'):runLabel}</button><div aria-live="polite" className="sr-only">{state.status==='available'?(ja?'アーキテクチャレビューが完了しました':'Architecture review completed'):''}</div>
  </section>}

function PaidAccess({paid,ja}:{paid:ReturnTypeOfUseArchitectureReview['paid'];ja:boolean}){const[email,setEmail]=useState('');const state=paid.access?.state;if(paid.authLoading||paid.offer===undefined)return <div role="status" aria-live="polite" className={box}>{ja?'アクセスを確認中…':'Checking access…'}</div>;if(!paid.offer?.enabled)return <Status title={ja?'有料レビューは現在無効です':'Paid review is currently disabled'} body={ja?'決定論的Preflightとexportは引き続き利用できます。':'Deterministic Preflight and export remain available.'}/>;if(!paid.session)return <div className={box}><p className="text-sm font-bold text-white">{ja?'サインインして利用':'Sign in to continue'}</p><label htmlFor="architecture-review-email" className="mt-3 block text-xs text-slate-300">{ja?'メールアドレス':'Email address'}</label><input id="architecture-review-email" type="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)} aria-describedby="architecture-review-auth-message" className="mt-1 min-h-11 w-full rounded-lg border border-slate-600 bg-slate-950 px-3 text-sm text-white"/><button type="button" disabled={paid.busy||!email} onClick={()=>paid.signIn(email)} className="mt-3 min-h-11 rounded-lg bg-indigo-500 px-4 text-sm font-bold text-white disabled:opacity-50">{ja?'サインインリンクをメールで受け取る':'Email me a sign-in link'}</button>{paid.message?<p id="architecture-review-auth-message" role="status" aria-live="polite" className="mt-2 text-xs text-slate-300">{paid.message}</p>:null}</div>;
if(paid.checkoutSyncing)return <Status title={ja?'サブスクリプションを確認中…':'Confirming your subscription…'} body={ja?'Stripeからの確認を待っています。URLだけではアクセスは付与されません。':'Waiting for Stripe confirmation. The return URL does not grant access.'}/>;
const quota=paid.access?.quota;const offer=paid.offer;const price=offer?.price?new Intl.NumberFormat(ja?'ja-JP':'en-US',{style:'currency',currency:offer.price.currency}).format(offer.price.unitAmount/100):null;const date=quota?new Intl.DateTimeFormat(ja?'ja-JP':'en-US',{dateStyle:'medium'}).format(new Date(quota.periodEnd)):null;
if(!state||state==='no_entitlement')return <div className={box}><p className="text-sm font-bold text-white">Architecture Review</p>{offer?.enabled?<><p className="mt-2 text-sm text-slate-200">{price} / {ja?'月':'month'} · {offer.includedReviews} {ja?'レビュー / 請求期間':'reviews per billing period'}</p><p className="mt-2 text-xs text-slate-300">{ja?'現在のworkflowを対象とした、Evidenceに基づくアーキテクチャレビューです。':'An evidence-grounded architecture review over the current workflow.'}</p><button type="button" disabled={paid.busy} onClick={paid.checkout} className="mt-3 min-h-11 rounded-lg bg-indigo-500 px-4 text-sm font-bold text-white disabled:opacity-50">{ja?'購読してArchitecture Reviewを利用':'Subscribe and unlock Architecture Review'}</button>{offer.policyUrls?<nav aria-label={ja?'有料サービスポリシー':'Paid service policies'} className="mt-3 flex flex-wrap gap-4 text-xs"><a className="min-h-11 py-3 text-teal-200" href={offer.policyUrls.terms} target="_blank" rel="noreferrer">{ja?'利用規約':'Terms'}</a><a className="min-h-11 py-3 text-teal-200" href={offer.policyUrls.privacy} target="_blank" rel="noreferrer">{ja?'プライバシー':'Privacy'}</a><a className="min-h-11 py-3 text-teal-200" href={offer.policyUrls.support} target="_blank" rel="noreferrer">{ja?'サポート':'Support'}</a></nav>:null}</>:<p className="mt-2 text-xs text-slate-300">{ja?'有料レビューは現在利用できません。無料の決定論的Preflightは引き続き利用できます。':'Paid review is currently unavailable. Free deterministic Preflight remains available.'}</p>}<button type="button" onClick={paid.signOut} className="mt-3 min-h-11 px-2 text-xs text-slate-300">{ja?'サインアウト':'Sign out'}</button>{paid.message?<p role="status" aria-live="polite" className="mt-2 text-xs text-slate-300">{paid.message}</p>:null}</div>;
if(state==='review_disabled')return <Status title={ja?'有料レビューは現在無効です':'Paid review is currently disabled'} body={ja?'決定論的Preflightとexportは引き続き利用できます。':'Deterministic Preflight and export remain available.'}/>;
if(state==='quota_exhausted')return <Status title={ja?'この請求期間のArchitecture Reviewを使い切りました':'You’ve used the included Architecture Reviews for this billing period.'} body={date?(ja?`次の確認日: ${date}`:`Period ends ${date}`):''} action={<button type="button" onClick={paid.manageBilling} className="min-h-11 text-xs font-bold text-teal-200">{ja?'請求管理':'Manage billing'}</button>}/>;
if(state==='billing_blocked'||state==='sync_degraded')return <Status title={state==='billing_blocked'?(ja?'請求情報の確認が必要です':'Billing needs attention'):(ja?'現在アクセスを確認できません':'Access cannot be verified right now')} body={ja?'AIレビューは一時停止しています。決定論的Preflightには影響しません。':'AI review is paused. Deterministic Preflight is unaffected.'} action={<><button type="button" onClick={paid.manageBilling} className="min-h-11 text-xs font-bold text-teal-200">{ja?'請求管理':'Manage billing'}</button><button type="button" onClick={paid.refreshBilling} className="ml-3 min-h-11 text-xs font-bold text-teal-200">{ja?'請求状態を更新':'Refresh billing status'}</button></>}/>;
return <div className={box}><p className="text-sm font-bold text-white">{quota?`${quota.remaining} / ${quota.limit} ${ja?'回残り':'remaining'}`:(ja?'利用可能':'Available')}</p>{date?<p className="mt-1 text-xs text-slate-300">{state==='active_canceling'?(ja?`${date}まで利用できます`:`Access remains available until ${date}`):(ja?`請求期間終了: ${date}`:`Billing period ends ${date}`)}</p>:null}<button type="button" onClick={paid.manageBilling} className="mt-2 min-h-11 text-xs font-bold text-teal-200">{ja?'請求管理':'Manage billing'}</button></div>}
function Status({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <div role="status" aria-live="polite" className={box}><p className="text-sm font-bold text-white">{title}</p><p className="mt-2 text-xs text-slate-300">{body}</p>{action}</div>}
function reviewFailureMessage(code:ArchitectureReviewErrorCode,ja:boolean){if(code==='request_cost_limit_exceeded')return ja?'このworkflowは現在の有料レビュー安全上限を超えています。Providerは実行されず、レビュー回数は使用されませんでした。':'This workflow exceeds the current paid-review safety limit. No provider review ran and no included review was used.';if(code==='accounting_unavailable')return ja?'安全に利用回数を確定できなかったため、結果は表示されません。利用回数は照合または解放されます。':'The result is hidden because usage could not be recorded safely. The allowance will be reconciled or released.';if(['provider_timeout','provider_error','rate_limited','invalid_reviewer_output'].includes(code))return ja?'レビューは完了せず、レビュー回数は使用されませんでした。決定論的Preflightには影響しません。':'The review was not completed and no included review was used. Deterministic Preflight remains available.';return ja?'レビューを完了できませんでした。決定論的Preflightには影響しません。':'The review could not be completed. Deterministic Preflight is unaffected.'}

function Result({result,ja,evidenceById,targetByKey,onLocate,locate}:any){const most=result.findings[0];const section=(title:string,body:any)=><section className={box}><h4 className="text-sm font-bold text-white">{title}</h4>{body}</section>;const finding=(item:any)=><article key={item.id} className="mt-3 rounded-xl border border-slate-700 p-3"><p className="text-xs font-bold text-indigo-200">{item.priority} · {item.class} · {item.knowledgeStatus}</p><p className="mt-2 text-sm font-semibold text-white">{item.problem}</p><p className="mt-2 text-xs text-slate-300"><strong>{ja?'理由':'Why'}:</strong> {item.why}</p><p className="mt-2 text-xs text-slate-300"><strong>{ja?'推奨':'Recommendation'}:</strong> {item.recommendation}</p><p className="mt-2 text-xs text-slate-300"><strong>{ja?'期待効果':'Expected effect'}:</strong> {item.expectedEffect}</p>{locate(item.targetRefs)?<button type="button" onClick={()=>onLocate(locate(item.targetRefs))} className="mt-3 min-h-11 rounded-lg border border-teal-700 px-3 text-xs font-bold text-teal-200">Locate</button>:null}</article>;
return <div className="space-y-4">{section(ja?'このworkflowが行うと考えられること':'What this workflow appears to do',<><p className="mt-2 text-sm text-slate-200">{result.intent.summary}</p><p className="mt-2 text-xs text-slate-400">{result.intent.knowledgeStatus}</p></>)}{section(ja?'最も重要な問題':'Most important issue',most?finding(most):<p className="mt-2 text-xs text-slate-300">{ja?'このヒューリスティックレビューでは、優先すべきアーキテクチャ所見は生成されませんでした。制約と根拠を引き続き確認してください。':'This heuristic review produced no prioritized architecture finding. Continue to review its evidence and limitations.'}</p>)}{section(ja?'推奨する方向性':'Recommended direction',<p className="mt-2 text-sm text-slate-200">{result.recommendedDirection}</p>)}{section(ja?'強み':'Strengths',result.strengths.length?result.strengths.map((x:any)=><article key={x.id} className="mt-3"><p className="text-sm font-semibold text-white">{x.statement}</p><p className="mt-1 text-xs text-slate-300">{x.whyItHelps}</p><p className="text-xs text-slate-500">{x.knowledgeStatus}</p></article>):<p className="mt-2 text-xs text-slate-400">—</p>)}{section(ja?'その他のアーキテクチャ所見':'Other architecture findings',result.findings.slice(1).length?result.findings.slice(1).map(finding):<p className="mt-2 text-xs text-slate-400">—</p>)}{section(ja?'不確実性':'Uncertainties',result.uncertainties.length?<ul className="mt-2 list-disc space-y-1 pl-4 text-xs text-slate-300">{result.uncertainties.map((x:any)=><li key={x.id}>{x.statement} · {x.knowledgeStatus}</li>)}</ul>:<p className="mt-2 text-xs text-slate-400">—</p>)}{section(ja?'レビューの制約':'Review limitations',<ul className="mt-2 list-disc pl-4 text-xs text-slate-300">{result.limitations.map((x:string)=><li key={x}>{x.replaceAll('_',' ')}</li>)}</ul>)}{section(ja?'Evidence / Reviewer詳細':'Evidence / Reviewer details',<details className="mt-2"><summary className="min-h-11 cursor-pointer text-xs font-bold text-teal-200">{ja?'根拠の詳細を表示':'Show evidence details'}</summary><div className="space-y-2">{[...new Set([...result.intent.evidenceRefs,...result.strengths.flatMap((x:any)=>x.evidenceRefs),...result.findings.flatMap((x:any)=>x.evidenceRefs),...result.uncertainties.flatMap((x:any)=>x.evidenceRefs)])].map((id:any)=>{const item:any=evidenceById.get(id);return item?<div key={id} className="rounded-lg bg-slate-950 p-2 text-xs"><p>{item.source} · {item.knowledgeStatus}</p><p className="text-slate-300">{item.summary}</p><p className="text-slate-500">{item.targetKeys.map((key:string)=>targetByKey.get(key)?.label??key).join(', ')}</p><p className="text-slate-600">{id} · {item.sourceVersion}{item.deterministicFindingRef?` · ${item.deterministicFindingRef}`:''}</p></div>:null})}<p className="text-xs text-slate-500">{result.reviewer.providerId} · {result.reviewer.modelId} · {result.reviewer.locale} · {result.reviewer.generatedAt}</p></div></details>)}</div>}
