'use client';

import type { ExecutionPreviewAgent, ExecutionPreviewStep } from '@/types/execution-preview';
import type { Language } from '@/lib/i18n/translations';
import { translations } from '@/lib/i18n/translations';

export type ExecutionPreviewLocateSource = 'task' | 'context' | 'assigned_agent' | 'direct_tool' | 'agent_section' | 'agent_tool' | 'manager';
export type ExecutionPreviewTargetType = 'task' | 'agent' | 'tool' | 'crew';

const LocateButton = ({ label, onClick }: { label: string; onClick: () => void }) => <button type="button" onClick={onClick} className="min-h-11 rounded-lg border border-cyan-700/60 px-3 text-xs font-bold text-cyan-200 hover:bg-cyan-950/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{label}</button>;

export function ExecutionPreviewStepCard({ step, agents, process, hasAsync, lang, onLocate }: { step: ExecutionPreviewStep; agents: readonly ExecutionPreviewAgent[]; process: 'sequential' | 'hierarchical'; hasAsync: boolean; lang: Language; onLocate: (type: ExecutionPreviewTargetType, id: string, source: ExecutionPreviewLocateSource) => void }) {
  const copy = translations[lang];
  const usePlanOrder = process === 'hierarchical' || hasAsync;
  const fixedAssignment = step.assignment.kind === 'fixed' ? step.assignment : undefined;
  const delegatedAssignment = step.assignment.kind === 'manager_delegated' ? step.assignment : undefined;
  const assigned = fixedAssignment ? agents.find((agent) => agent.agentId === fixedAssignment.agent.agentId) : undefined;
  return <li className="rounded-2xl border border-slate-700 bg-slate-900/75 p-4">
    <div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-wider text-cyan-300">{usePlanOrder ? copy.executionPreviewPlanOrder : copy.executionPreviewStep} {step.planOrder}</p><h3 className="mt-1 text-sm font-extrabold text-white">{step.label}</h3></div><LocateButton label={copy.executionPreviewLocateTask} onClick={() => onLocate('task', step.taskId, 'task')} /></div>
    {step.asyncExecution ? <span className="mt-3 inline-flex rounded-full bg-indigo-950 px-2 py-1 text-[10px] font-bold text-indigo-200">{copy.executionPreviewAsyncEnabled}</span> : null}
    <section className="mt-4 rounded-xl bg-slate-950/70 p-3">
      {fixedAssignment ? <><p className="text-[10px] uppercase text-slate-500">{copy.executionPreviewAssignedAgent}</p><p className="mt-1 text-xs font-bold text-slate-100">{fixedAssignment.agent.label}</p><p className="text-[11px] text-slate-400">{fixedAssignment.agent.role}</p><p className="mt-1 text-[10px] text-cyan-300">{copy.executionPreviewFixedAssignment}{assigned ? ` · ${assigned.model}` : ''}</p><LocateButton label={copy.executionPreviewLocateAgent} onClick={() => onLocate('agent', fixedAssignment.agent.agentId, 'assigned_agent')} /></> : <><p className="text-xs font-bold text-indigo-200">{copy.executionPreviewManagerDelegated}</p>{delegatedAssignment?.configuredAgent ? <div className="mt-2"><p className="text-[10px] uppercase text-slate-500">{copy.executionPreviewConfiguredAgent}</p><p className="text-xs text-slate-200">{delegatedAssignment.configuredAgent.label} · {delegatedAssignment.configuredAgent.role}</p><p className="mt-1 text-[10px] leading-relaxed text-slate-500">{copy.executionPreviewConfiguredAgentNote}</p><LocateButton label={copy.executionPreviewLocateAgent} onClick={() => onLocate('agent', delegatedAssignment.configuredAgent!.agentId, 'assigned_agent')} /></div> : null}</>}
    </section>
    <section className="mt-3"><h4 className="text-[10px] font-bold uppercase text-slate-500">{copy.executionPreviewContextFrom}</h4>{step.context.length ? <div className="mt-2 flex flex-wrap gap-2">{step.context.map((item) => <button type="button" key={item.taskId} onClick={() => onLocate('task', item.taskId, 'context')} className="min-h-11 rounded-lg bg-slate-800 px-3 text-xs text-slate-200 hover:bg-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{item.label}</button>)}</div> : <p className="mt-1 text-xs text-slate-600">{copy.executionPreviewNone}</p>}</section>
    <section className="mt-3"><h4 className="text-[10px] font-bold uppercase text-slate-500">{copy.executionPreviewDirectTools}</h4>{step.directTools.length ? <div className="mt-2 flex flex-wrap gap-2">{step.directTools.map((item) => <button type="button" key={item.toolId} onClick={() => onLocate('tool', item.toolId, 'direct_tool')} className="min-h-11 rounded-lg bg-cyan-950/50 px-3 text-xs text-cyan-100 hover:bg-cyan-900/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{item.label} · {item.toolType}</button>)}</div> : <p className="mt-1 text-xs text-slate-600">{copy.executionPreviewNone}</p>}</section>
    <details className="mt-4 border-t border-slate-800 pt-3"><summary className="cursor-pointer text-xs font-bold text-slate-300">{copy.executionPreviewDetails}</summary><dl className="mt-3 space-y-2 text-xs"><div><dt className="text-slate-500">{copy.description}</dt><dd className="whitespace-pre-wrap text-slate-300">{step.description}</dd></div><div><dt className="text-slate-500">{copy.expectedOutput}</dt><dd className="whitespace-pre-wrap text-slate-300">{step.expectedOutput}</dd></div><div><dt className="text-slate-500">{copy.outputFormat}</dt><dd className="text-slate-300">{step.outputFormat === 'json' ? copy.executionPreviewStructuredJson : copy.executionPreviewText}</dd></div><div><dt className="text-slate-500">{copy.humanApproval}</dt><dd className="text-slate-300">{step.humanInput ? copy.executionPreviewYes : copy.executionPreviewNo}</dd></div><div><dt className="text-slate-500">{copy.markdownOutput}</dt><dd className="text-slate-300">{step.markdown ? copy.executionPreviewYes : copy.executionPreviewNo}</dd></div>{step.outputFile !== undefined ? <div><dt className="text-slate-500">{copy.outputFile}</dt><dd className="break-all text-slate-300">{step.outputFile}</dd></div> : null}</dl></details>
  </li>;
}
